export const VOCABULARY = [
  {"en":"hello","rom":"hello","translated":"hello","topic":"Basics & Greetings"},
  {"en":"thank you","rom":"thank you","translated":"thank you","topic":"Basics & Greetings"},
  {"en":"yes","rom":"yes","translated":"yes","topic":"Basics & Greetings"},
  {"en":"no","rom":"no","translated":"no","topic":"Basics & Greetings"},
  {"en":"apple","rom":"apple","translated":"apple","topic":"Food & Drink"},
  {"en":"water","rom":"water","translated":"water","topic":"Food & Drink"},
  {"en":"cat","rom":"cat","translated":"cat","topic":"Nature & Animals"},
  {"en":"dog","rom":"dog","translated":"dog","topic":"Nature & Animals"},
  {"en":"please","topic":"Basics & Greetings"},
  {"en":"excuse me","topic":"Basics & Greetings"},
  {"en":"good morning","topic":"Basics & Greetings"},
  {"en":"good night","topic":"Basics & Greetings"},
  {"en":"family","topic":"People & Family"},
  {"en":"mother","topic":"People & Family"},
  {"en":"father","topic":"People & Family"},
  {"en":"friend","topic":"People & Family"},
  {"en":"person","topic":"People & Family"},
  {"en":"man","topic":"People & Family"},
  {"en":"woman","topic":"People & Family"},
  {"en":"child","topic":"People & Family"},
  {"en":"parents","topic":"People & Family"},
  {"en":"brother","topic":"People & Family"},
  {"en":"sister","topic":"People & Family"},
  {"en":"grandfather","topic":"People & Family"},
  {"en":"grandmother","topic":"People & Family"},
  {"en":"time","topic":"Time & Calendar"},
  {"en":"today","topic":"Time & Calendar"},
  {"en":"tomorrow","topic":"Time & Calendar"},
  {"en":"yesterday","topic":"Time & Calendar"},
  {"en":"day","topic":"Time & Calendar"},
  {"en":"week","topic":"Time & Calendar"},
  {"en":"month","topic":"Time & Calendar"},
  {"en":"year","topic":"Time & Calendar"},
  {"en":"morning","topic":"Time & Calendar"},
  {"en":"afternoon","topic":"Time & Calendar"},
  {"en":"evening","topic":"Time & Calendar"},
  {"en":"night","topic":"Time & Calendar"},
  {"en":"always","topic":"Time & Calendar"},
  {"en":"never","topic":"Time & Calendar"},
  {"en":"now","topic":"Time & Calendar"},
  {"en":"food","topic":"Food & Drink"},
  {"en":"bread","topic":"Food & Drink"},
  {"en":"meat","topic":"Food & Drink"},
  {"en":"fish","topic":"Food & Drink"},
  {"en":"cheese","topic":"Food & Drink"},
  {"en":"vegetable","topic":"Food & Drink"},
  {"en":"fruit","topic":"Food & Drink"},
  {"en":"coffee","topic":"Food & Drink"},
  {"en":"tea","topic":"Food & Drink"},
  {"en":"milk","topic":"Food & Drink"},
  {"en":"beer","topic":"Food & Drink"},
  {"en":"wine","topic":"Food & Drink"},
  {"en":"breakfast","topic":"Food & Drink"},
  {"en":"lunch","topic":"Food & Drink"},
  {"en":"dinner","topic":"Food & Drink"},
  {"en":"house","topic":"House & Home"},
  {"en":"room","topic":"House & Home"},
  {"en":"door","topic":"House & Home"},
  {"en":"window","topic":"House & Home"},
  {"en":"bed","topic":"House & Home"},
  {"en":"table","topic":"House & Home"},
  {"en":"chair","topic":"House & Home"},
  {"en":"kitchen","topic":"House & Home"},
  {"en":"bathroom","topic":"House & Home"},
  {"en":"bird","topic":"Nature & Animals"},
  {"en":"tree","topic":"Nature & Animals"},
  {"en":"sun","topic":"Nature & Animals"},
  {"en":"moon","topic":"Nature & Animals"},
  {"en":"flower","topic":"Nature & Animals"},
  {"en":"sky","topic":"Nature & Animals"},
  {"en":"sea","topic":"Nature & Animals"},
  {"en":"mountain","topic":"Nature & Animals"},
  {"en":"city","topic":"City & Places"},
  {"en":"street","topic":"City & Places"},
  {"en":"school","topic":"City & Places"},
  {"en":"hospital","topic":"City & Places"},
  {"en":"store","topic":"City & Places"},
  {"en":"restaurant","topic":"City & Places"},
  {"en":"station","topic":"City & Places"},
  {"en":"park","topic":"City & Places"},
  {"en":"car","topic":"Transportation"},
  {"en":"bus","topic":"Transportation"},
  {"en":"train","topic":"Transportation"},
  {"en":"airplane","topic":"Transportation"},
  {"en":"boat","topic":"Transportation"},
  {"en":"to be (permanent)","topic":"Action Verbs"},
  {"en":"to be (temporary)","topic":"Action Verbs"},
  {"en":"to have","topic":"Action Verbs"},
  {"en":"to do / to make","topic":"Action Verbs"},
  {"en":"to go","topic":"Action Verbs"},
  {"en":"to come","topic":"Action Verbs"},
  {"en":"to see","topic":"Action Verbs"},
  {"en":"to speak","topic":"Action Verbs"},
  {"en":"to eat","topic":"Action Verbs"},
  {"en":"to drink","topic":"Action Verbs"},
  {"en":"to sleep","topic":"Action Verbs"},
  {"en":"to write","topic":"Action Verbs"},
  {"en":"to read","topic":"Action Verbs"},
  {"en":"to walk","topic":"Action Verbs"},
  {"en":"to run","topic":"Action Verbs"},
  {"en":"to buy","topic":"Action Verbs"},
  {"en":"to sell","topic":"Action Verbs"},
  {"en":"to understand","topic":"Action Verbs"},
  {"en":"to know (a fact)","topic":"Action Verbs"},
  {"en":"good","topic":"Descriptive (Adjectives)"},
  {"en":"bad","topic":"Descriptive (Adjectives)"},
  {"en":"big","topic":"Descriptive (Adjectives)"},
  {"en":"small","topic":"Descriptive (Adjectives)"},
  {"en":"hot","topic":"Descriptive (Adjectives)"},
  {"en":"cold","topic":"Descriptive (Adjectives)"},
  {"en":"new","topic":"Descriptive (Adjectives)"},
  {"en":"old","topic":"Descriptive (Adjectives)"},
  {"en":"beautiful","topic":"Descriptive (Adjectives)"},
  {"en":"fast","topic":"Descriptive (Adjectives)"},
  {"en":"slow","topic":"Descriptive (Adjectives)"},
  {"en":"happy","topic":"Descriptive (Adjectives)"},
  {"en":"sad","topic":"Descriptive (Adjectives)"},
  {"en":"red","topic":"Colors & Shapes"},
  {"en":"blue","topic":"Colors & Shapes"},
  {"en":"green","topic":"Colors & Shapes"},
  {"en":"yellow","topic":"Colors & Shapes"},
  {"en":"black","topic":"Colors & Shapes"},
  {"en":"white","topic":"Colors & Shapes"},
  {"en":"one","topic":"Numbers & Math"},
  {"en":"two","topic":"Numbers & Math"},
  {"en":"three","topic":"Numbers & Math"},
  {"en":"four","topic":"Numbers & Math"},
  {"en":"five","topic":"Numbers & Math"},
  {"en":"six","topic":"Numbers & Math"},
  {"en":"seven","topic":"Numbers & Math"},
  {"en":"eight","topic":"Numbers & Math"},
  {"en":"nine","topic":"Numbers & Math"},
  {"en":"ten","topic":"Numbers & Math"},
  {"en":"book","topic":"Misc & Core Vocab"},
  {"en":"pen","topic":"Misc & Core Vocab"},
  {"en":"money","topic":"Misc & Core Vocab"},
  {"en":"love","topic":"Abstract Concepts"},
  {"en":"world","topic":"Abstract Concepts"},
  {"en":"life","topic":"Abstract Concepts"}
];

export const CONJUGATIONS = [];
export const GRAMMAR_QUESTIONS = [
    {
        sentence: "They left their jackets over there because they're going inside.",
        en: "Pronoun usage",
        question: "Which of the following correctly describes 'their', 'there', and 'they're'?",
        options: [
            "'Their' is a place, 'there' is possessive, 'they're' is a contraction.",
            "'Their' is possessive, 'there' is a place, 'they're' is a contraction.",
            "'Their' is a contraction, 'there' is possessive, 'they're' is a place.",
            "They are entirely interchangeable."
        ],
        answer: 1,
        explanation: "'Their' implies ownership, 'there' refers to location, and 'they're' is short for 'they are'."
    },
    {
        sentence: "How much water do we need, and how many apples should I buy?",
        en: "Quantifiers",
        question: "Why do we use 'much' for water and 'many' for apples?",
        options: [
            "'Much' is for liquids, 'many' is for solids.",
            "'Much' is used in questions, 'many' is for statements.",
            "'Much' is for uncountable nouns, 'many' is for countable nouns.",
            "'Much' is plural, 'many' is singular."
        ],
        answer: 2,
        explanation: "Water cannot be individually counted (uncountable), so we use 'much'. Apples can be counted individually, so we use 'many'."
    },
    {
        sentence: "I have been living in London for five years.",
        en: "Verb Tenses",
        question: "What tense is used in this sentence?",
        options: [
            "Present Simple",
            "Present Perfect Continuous",
            "Past Continuous",
            "Future Perfect"
        ],
        answer: 1,
        explanation: "'Have been living' is the Present Perfect Continuous tense. It is used to describe an action that started in the past and continues into the present."
    },
    {
        sentence: "She is the woman whom I met yesterday.",
        en: "Relative Pronouns",
        question: "Why is 'whom' used instead of 'who'?",
        options: [
            "'Whom' is the subject of the clause.",
            "'Whom' is the object of the verb 'met'.",
            "'Who' can only be used for men.",
            "'Whom' is plural."
        ],
        answer: 1,
        explanation: "'Whom' functions as the object of the verb. If the pronoun is the subject, use 'who' (e.g., 'She is the woman who met me')."
    },
    {
        sentence: "An apple a day keeps the doctor away.",
        en: "Articles",
        question: "Why do we use 'an' before apple instead of 'a'?",
        options: [
            "Because 'apple' is an important word.",
            "Because 'apple' starts with a vowel sound.",
            "Because 'a' is only for plural words.",
            "It is a random exception."
        ],
        answer: 1,
        explanation: "In English, the indefinite article 'an' is used before words that begin with a vowel sound to make pronunciation smoother."
    }
];
export const IDIOMS = [
    {"phrase":"Hello, how are you?","meaning":"Hello, how are you?","category":"Conversational"},
    {"phrase":"I am doing great, thank you.","meaning":"I am doing great, thank you.","category":"Conversational"},
    {"phrase":"What is your name?","meaning":"What is your name?","category":"Conversational"},
    {"phrase":"My name is...","meaning":"My name is...","category":"Conversational"},
    {"phrase":"Nice to meet you.","meaning":"Nice to meet you.","category":"Conversational"},
    {"phrase":"Where are you from?","meaning":"Where are you from?","category":"Conversational"},
    {"phrase":"I am from...","meaning":"I am from...","category":"Conversational"},
    {"phrase":"Do you speak English?","meaning":"Do you speak English?","category":"Conversational"},
    {"phrase":"I speak a little bit.","meaning":"I speak a little bit.","category":"Conversational"},
    {"phrase":"I don't understand.","meaning":"I don't understand.","category":"Conversational"},
    {"phrase":"Can you speak more slowly, please?","meaning":"Can you speak more slowly, please?","category":"Conversational"},
    {"phrase":"Can you repeat that?","meaning":"Can you repeat that?","category":"Conversational"},
    {"phrase":"Excuse me, where is the bathroom?","meaning":"Excuse me, where is the bathroom?","category":"Conversational"},
    {"phrase":"How much does this cost?","meaning":"How much does this cost?","category":"Conversational"},
    {"phrase":"I would like to order.","meaning":"I would like to order.","category":"Conversational"},
    {"phrase":"The check, please.","meaning":"The check, please.","category":"Conversational"},
    {"phrase":"Can I pay with a credit card?","meaning":"Can I pay with a credit card?","category":"Conversational"},
    {"phrase":"What time is it?","meaning":"What time is it?","category":"Conversational"},
    {"phrase":"I need some help, please.","meaning":"I need some help, please.","category":"Conversational"},
    {"phrase":"I am lost.","meaning":"I am lost.","category":"Conversational"},
    {"phrase":"Have a great day!","meaning":"Have a great day!","category":"Conversational"},
    {"phrase":"I love learning languages.","meaning":"I love learning languages.","category":"Conversational"},
    {"phrase":"What are you doing this weekend?","meaning":"What are you doing this weekend?","category":"Conversational"},
    {"phrase":"I am feeling a bit tired.","meaning":"I am feeling a bit tired.","category":"Conversational"},
    {"phrase":"Are you hungry?","meaning":"Are you hungry?","category":"Conversational"},
    {"phrase":"This is very delicious.","meaning":"This is very delicious.","category":"Conversational"},
    {"phrase":"I will call you later.","meaning":"I will call you later.","category":"Conversational"},
    {"phrase":"What is your favorite food?","meaning":"What is your favorite food?","category":"Conversational"},
    {"phrase":"How is the weather today?","meaning":"How is the weather today?","category":"Conversational"},
    {"phrase":"I am sorry, I am late.","meaning":"I am sorry, I am late.","category":"Conversational"}
];
export const CONVERSATION_TOPICS = [
    "Your favorite travel destinations",
    "The best food you've ever eaten",
    "What you do for a living or study",
    "Your hobbies and interests",
    "A memorable experience from childhood",
];
export const SENTENCE_BUILD_PROMPTS = [
    { prompt: "Describe what you did this morning.", en_hint: "Use the past simple tense (e.g., I woke up, I ate)", topic: "daily routine" },
    { prompt: "Say what you would do if you won the lottery.", en_hint: "Use the second conditional (if + past, would + verb)", topic: "hypothetical" },
    { prompt: "Ask a friend if they want to get coffee later.", en_hint: "Use 'Do you want to...' or 'Would you like to...'", topic: "invitation" },
    { prompt: "Explain why you are studying English.", en_hint: "Use 'because' + reason", topic: "study" },
    { prompt: "Describe your favorite movie and why you like it.", en_hint: "Use descriptive adjectives and present simple", topic: "entertainment" },
];
export const VIDEOS = [];
export const CULTURE = [];

export const PROGRESSION = [
    "Basics & Greetings",
    "Food & Drink",
    "Nature & Animals",
    "Numbers & Math",
    "Time & Calendar",
    "Action Verbs",
    "Descriptive (Adjectives)",
    "People & Family",
    "House & Home",
    "City & Places",
    "Transportation",
    "Abstract Concepts",
    "Misc & Core Vocab"
];
