export const VOCABULARY = [
  {"fr":"bonjour","rom":"bon-zhoor","en":"hello","topic":"Basics & Greetings"},
  {"fr":"merci","rom":"mer-see","en":"thank you","topic":"Basics & Greetings"},
  {"fr":"oui","rom":"wee","en":"yes","topic":"Basics & Greetings"},
  {"fr":"non","rom":"nohn","en":"no","topic":"Basics & Greetings"},
  {"fr":"pomme","rom":"puhm","en":"apple","topic":"Food & Drink"},
  {"fr":"eau","rom":"oh","en":"water","topic":"Food & Drink"},
  {"fr":"chat","rom":"shah","en":"cat","topic":"Nature & Animals"},
  {"fr":"chien","rom":"shee-en","en":"dog","topic":"Nature & Animals"},
  {"fr":"s'il vous plaît","en":"please","topic":"Basics & Greetings"},
  {"fr":"excusez-moi","en":"excuse me","topic":"Basics & Greetings"},
  {"fr":"bonjour","en":"good morning","topic":"Basics & Greetings"},
  {"fr":"bonne nuit","en":"good night","topic":"Basics & Greetings"},
  {"fr":"famille","en":"family","topic":"People & Family"},
  {"fr":"mère","en":"mother","topic":"People & Family"},
  {"fr":"père","en":"father","topic":"People & Family"},
  {"fr":"ami","en":"friend","topic":"People & Family"},
  {"fr":"personne","en":"person","topic":"People & Family"},
  {"fr":"homme","en":"man","topic":"People & Family"},
  {"fr":"femme","en":"woman","topic":"People & Family"},
  {"fr":"enfant","en":"child","topic":"People & Family"},
  {"fr":"parents","en":"parents","topic":"People & Family"},
  {"fr":"frère","en":"brother","topic":"People & Family"},
  {"fr":"sœur","en":"sister","topic":"People & Family"},
  {"fr":"grand-père","en":"grandfather","topic":"People & Family"},
  {"fr":"grand-mère","en":"grandmother","topic":"People & Family"},
  {"fr":"temps","en":"time","topic":"Time & Calendar"},
  {"fr":"aujourd'hui","en":"today","topic":"Time & Calendar"},
  {"fr":"demain","en":"tomorrow","topic":"Time & Calendar"},
  {"fr":"hier","en":"yesterday","topic":"Time & Calendar"},
  {"fr":"jour","en":"day","topic":"Time & Calendar"},
  {"fr":"semaine","en":"week","topic":"Time & Calendar"},
  {"fr":"mois","en":"month","topic":"Time & Calendar"},
  {"fr":"année","en":"year","topic":"Time & Calendar"},
  {"fr":"matin","en":"morning","topic":"Time & Calendar"},
  {"fr":"après-midi","en":"afternoon","topic":"Time & Calendar"},
  {"fr":"soir","en":"evening","topic":"Time & Calendar"},
  {"fr":"nuit","en":"night","topic":"Time & Calendar"},
  {"fr":"toujours","en":"always","topic":"Time & Calendar"},
  {"fr":"jamais","en":"never","topic":"Time & Calendar"},
  {"fr":"maintenant","en":"now","topic":"Time & Calendar"},
  {"fr":"nourriture","en":"food","topic":"Food & Drink"},
  {"fr":"pain","en":"bread","topic":"Food & Drink"},
  {"fr":"viande","en":"meat","topic":"Food & Drink"},
  {"fr":"poisson","en":"fish","topic":"Food & Drink"},
  {"fr":"fromage","en":"cheese","topic":"Food & Drink"},
  {"fr":"légume","en":"vegetable","topic":"Food & Drink"},
  {"fr":"fruit","en":"fruit","topic":"Food & Drink"},
  {"fr":"café","en":"coffee","topic":"Food & Drink"},
  {"fr":"thé","en":"tea","topic":"Food & Drink"},
  {"fr":"lait","en":"milk","topic":"Food & Drink"},
  {"fr":"bière","en":"beer","topic":"Food & Drink"},
  {"fr":"vin","en":"wine","topic":"Food & Drink"},
  {"fr":"petit-déjeuner","en":"breakfast","topic":"Food & Drink"},
  {"fr":"déjeuner","en":"lunch","topic":"Food & Drink"},
  {"fr":"dîner","en":"dinner","topic":"Food & Drink"},
  {"fr":"maison","en":"house","topic":"House & Home"},
  {"fr":"chambre","en":"room","topic":"House & Home"},
  {"fr":"porte","en":"door","topic":"House & Home"},
  {"fr":"fenêtre","en":"window","topic":"House & Home"},
  {"fr":"lit","en":"bed","topic":"House & Home"},
  {"fr":"table","en":"table","topic":"House & Home"},
  {"fr":"chaise","en":"chair","topic":"House & Home"},
  {"fr":"cuisine","en":"kitchen","topic":"House & Home"},
  {"fr":"salle de bain","en":"bathroom","topic":"House & Home"},
  {"fr":"oiseau","en":"bird","topic":"Nature & Animals"},
  {"fr":"arbre","en":"tree","topic":"Nature & Animals"},
  {"fr":"soleil","en":"sun","topic":"Nature & Animals"},
  {"fr":"lune","en":"moon","topic":"Nature & Animals"},
  {"fr":"fleur","en":"flower","topic":"Nature & Animals"},
  {"fr":"ciel","en":"sky","topic":"Nature & Animals"},
  {"fr":"mer","en":"sea","topic":"Nature & Animals"},
  {"fr":"montagne","en":"mountain","topic":"Nature & Animals"},
  {"fr":"ville","en":"city","topic":"City & Places"},
  {"fr":"rue","en":"street","topic":"City & Places"},
  {"fr":"école","en":"school","topic":"City & Places"},
  {"fr":"hôpital","en":"hospital","topic":"City & Places"},
  {"fr":"magasin","en":"store","topic":"City & Places"},
  {"fr":"restaurant","en":"restaurant","topic":"City & Places"},
  {"fr":"gare","en":"station","topic":"City & Places"},
  {"fr":"parc","en":"park","topic":"City & Places"},
  {"fr":"voiture","en":"car","topic":"Transportation"},
  {"fr":"bus","en":"bus","topic":"Transportation"},
  {"fr":"train","en":"train","topic":"Transportation"},
  {"fr":"avion","en":"airplane","topic":"Transportation"},
  {"fr":"bateau","en":"boat","topic":"Transportation"},
  {"fr":"être","en":"to be (permanent)","topic":"Action Verbs"},
  {"fr":"être","en":"to be (temporary)","topic":"Action Verbs"},
  {"fr":"avoir","en":"to have","topic":"Action Verbs"},
  {"fr":"faire","en":"to do / to make","topic":"Action Verbs"},
  {"fr":"aller","en":"to go","topic":"Action Verbs"},
  {"fr":"venir","en":"to come","topic":"Action Verbs"},
  {"fr":"voir","en":"to see","topic":"Action Verbs"},
  {"fr":"parler","en":"to speak","topic":"Action Verbs"},
  {"fr":"manger","en":"to eat","topic":"Action Verbs"},
  {"fr":"boire","en":"to drink","topic":"Action Verbs"},
  {"fr":"dormir","en":"to sleep","topic":"Action Verbs"},
  {"fr":"écrire","en":"to write","topic":"Action Verbs"},
  {"fr":"lire","en":"to read","topic":"Action Verbs"},
  {"fr":"marcher","en":"to walk","topic":"Action Verbs"},
  {"fr":"courir","en":"to run","topic":"Action Verbs"},
  {"fr":"acheter","en":"to buy","topic":"Action Verbs"},
  {"fr":"vendre","en":"to sell","topic":"Action Verbs"},
  {"fr":"comprendre","en":"to understand","topic":"Action Verbs"},
  {"fr":"savoir","en":"to know (a fact)","topic":"Action Verbs"},
  {"fr":"bon","en":"good","topic":"Descriptive (Adjectives)"},
  {"fr":"mauvais","en":"bad","topic":"Descriptive (Adjectives)"},
  {"fr":"grand","en":"big","topic":"Descriptive (Adjectives)"},
  {"fr":"petit","en":"small","topic":"Descriptive (Adjectives)"},
  {"fr":"chaud","en":"hot","topic":"Descriptive (Adjectives)"},
  {"fr":"froid","en":"cold","topic":"Descriptive (Adjectives)"},
  {"fr":"nouveau","en":"new","topic":"Descriptive (Adjectives)"},
  {"fr":"vieux","en":"old","topic":"Descriptive (Adjectives)"},
  {"fr":"beau","en":"beautiful","topic":"Descriptive (Adjectives)"},
  {"fr":"rapide","en":"fast","topic":"Descriptive (Adjectives)"},
  {"fr":"lent","en":"slow","topic":"Descriptive (Adjectives)"},
  {"fr":"heureux","en":"happy","topic":"Descriptive (Adjectives)"},
  {"fr":"triste","en":"sad","topic":"Descriptive (Adjectives)"},
  {"fr":"rouge","en":"red","topic":"Colors & Shapes"},
  {"fr":"bleu","en":"blue","topic":"Colors & Shapes"},
  {"fr":"vert","en":"green","topic":"Colors & Shapes"},
  {"fr":"jaune","en":"yellow","topic":"Colors & Shapes"},
  {"fr":"noir","en":"black","topic":"Colors & Shapes"},
  {"fr":"blanc","en":"white","topic":"Colors & Shapes"},
  {"fr":"un","en":"one","topic":"Numbers & Math"},
  {"fr":"deux","en":"two","topic":"Numbers & Math"},
  {"fr":"trois","en":"three","topic":"Numbers & Math"},
  {"fr":"quatre","en":"four","topic":"Numbers & Math"},
  {"fr":"cinq","en":"five","topic":"Numbers & Math"},
  {"fr":"six","en":"six","topic":"Numbers & Math"},
  {"fr":"sept","en":"seven","topic":"Numbers & Math"},
  {"fr":"huit","en":"eight","topic":"Numbers & Math"},
  {"fr":"neuf","en":"nine","topic":"Numbers & Math"},
  {"fr":"dix","en":"ten","topic":"Numbers & Math"},
  {"fr":"livre","en":"book","topic":"Misc & Core Vocab"},
  {"fr":"stylo","en":"pen","topic":"Misc & Core Vocab"},
  {"fr":"argent","en":"money","topic":"Misc & Core Vocab"},
  {"fr":"amour","en":"love","topic":"Abstract Concepts"},
  {"fr":"monde","en":"world","topic":"Abstract Concepts"},
  {"fr":"vie","en":"life","topic":"Abstract Concepts"}
];

export const CONJUGATIONS = [];
export const GRAMMAR_QUESTIONS = [
    {
        sentence: "Je suis étudiant.",
        en: "I am a student.",
        question: "Why is there no article ('un' or 'une') before 'étudiant'?",
        options: [
            "Professions take no article after the verb 'être' in French.",
            "It is a masculine noun.",
            "The article is optional.",
            "Because 'étudiant' starts with a vowel."
        ],
        answer: 0,
        explanation: "In French, when stating someone's profession using the normal subject + être construction (e.g., Je suis étudiant, Il est médecin), the indefinite article is omitted."
    }
];
export const IDIOMS = [
    {
        phrase: "Poser un lapin",
        literal: "To put a rabbit",
        meaning: "To stand someone up",
        usage: "Used when someone didn't show up for a date or meeting.",
        example: "Il ne viendra pas, je crois qu'il m'a posé un lapin.",
        category: "Social Life"
    },
    {
        phrase: "Avoir le cafard",
        literal: "To have the cockroach",
        meaning: "To feel down / depressed / homesick",
        usage: "To describe feeling a bit sad or melancholic.",
        example: "J'ai un peu le cafard aujourd'hui avec ce temps.",
        category: "Emotions"
    },
    {
        phrase: "Revenons à nos moutons",
        literal: "Let us return to our sheep",
        meaning: "Let's get back to the topic at hand",
        usage: "When a conversation has derailed and you want to refocus.",
        example: "Bref, revenons à nos moutons, qu'en est-il du projet ?",
        category: "Communication"
    },
    {
        phrase: "Quand les poules auront des dents",
        literal: "When chickens will have teeth",
        meaning: "When pigs fly / never",
        usage: "To express something that is impossible or highly unlikely.",
        example: "Il sera à l'heure quand les poules auront des dents.",
        category: "Opportunity"
    },
    {
        phrase: "Couper les cheveux en quatre",
        literal: "To cut hair in four",
        meaning: "To split hairs / to overcomplicate things",
        usage: "When someone is being unnecessarily pedantic or overthinking.",
        example: "Ne coupe pas les cheveux en quatre, c'est simple !",
        category: "Personality & Mind"
    },
    {
        phrase: "Avoir la moutarde qui monte au nez",
        literal: "To have mustard going up the nose",
        meaning: "To lose one's temper / get angry",
        usage: "When someone is starting to lose their patience.",
        example: "Arrête de l'embêter, la moutarde lui monte au nez.",
        category: "Anger"
    },
    {
        phrase: "Coûter les yeux de la tête",
        literal: "To cost the eyes of the head",
        meaning: "To cost an arm and a leg / be extremely expensive",
        usage: "To complain about a high price.",
        example: "Cette voiture m'a coûté les yeux de la tête.",
        category: "Money"
    },
    {
        phrase: "Jeter l'éponge",
        literal: "To throw the sponge",
        meaning: "To throw in the towel / give up",
        usage: "When someone abandons trying to do something difficult.",
        example: "C'est trop dur, je jette l'éponge.",
        category: "Work & Business"
    },
    {
        phrase: "Tomber dans les pommes",
        literal: "To fall in the apples",
        meaning: "To faint or pass out",
        usage: "When someone loses consciousness.",
        example: "Il a vu du sang et il est tombé dans les pommes.",
        category: "Food & Daily Life"
    },
    {
        phrase: "Appeler un chat un chat",
        literal: "To call a cat a cat",
        meaning: "To call a spade a spade / speak plainly",
        usage: "To speak directly and honestly about something unpleasant.",
        example: "Il faut appeler un chat un chat, c'est un échec.",
        category: "Communication"
    }
];
export const CONVERSATION_TOPICS = [
    "Tes passe-temps (Your hobbies)",
    "Nourriture préférée (Favorite food)",
    "Projets d'avenir (Plans for the future)"
];
export const SENTENCE_BUILD_PROMPTS = [
    { prompt: "Describe what you did this morning.", en_hint: "Use the passé composé.", topic: "daily routine" }
];
export const VIDEOS = [];
export const CULTURE = [];

export const PROGRESSION = [
    "Basics & Greetings",
    "Food & Drink",
    "Nature & Animals",
    "Numbers & Math",
    "Time & Calendar",
    "Action Verbs",
    "Descriptive (Adjectives)",
    "People & Family",
    "House & Home",
    "City & Places",
    "Transportation",
    "Abstract Concepts",
    "Misc & Core Vocab"
];
