export const ALPHABET_CATEGORIES = [
    {
        id: "alefbet_consonants",
        label: "Alef-Bet (Consonants)",
        items: [
            { kr: "א", rom: "Alef", exp: "Silent letter. Takes the sound of the vowel attached to it." },
            { kr: "ב", rom: "Bet / Vet", exp: "Like 'b' in 'boy' (with a dot/dagesh) or 'v' in 'van' (without)." },
            { kr: "ג", rom: "Gimel", exp: "Like 'g' in 'go'." },
            { kr: "ד", rom: "Dalet", exp: "Like 'd' in 'dog'." },
            { kr: "ה", rom: "Hei", exp: "Like 'h' in 'hat'." },
            { kr: "ו", rom: "Vav", exp: "Like 'v' in 'van' (also used as vowels 'o' or 'u')." },
            { kr: "ז", rom: "Zayin", exp: "Like 'z' in 'zoo'." },
            { kr: "ח", rom: "Chet", exp: "Guttural sound, like Scottish 'loch' or German 'Bach'." },
            { kr: "ט", rom: "Tet", exp: "Like 't' in 'top'." },
            { kr: "י", rom: "Yod", exp: "Like 'y' in 'yes'." },
            { kr: "כ", rom: "Kaf / Khaf", exp: "Like 'k' (with dot) or guttural 'ch' (without dot)." },
            { kr: "ל", rom: "Lamed", exp: "Like 'l' in 'lion'." },
            { kr: "מ", rom: "Mem", exp: "Like 'm' in 'mother'." },
            { kr: "נ", rom: "Nun", exp: "Like 'n' in 'now'." },
            { kr: "ס", rom: "Samekh", exp: "Like 's' in 'sun'." },
            { kr: "ע", rom: "Ayin", exp: "Silent / guttural stop. Similar to Alef in modern Hebrew." },
            { kr: "פ", rom: "Pei / Fei", exp: "Like 'p' in 'park' (with dot) or 'f' in 'farm' (without)." },
            { kr: "צ", rom: "Tsadi", exp: "Like 'ts' in 'cats'." },
            { kr: "ק", rom: "Qof", exp: "Like 'k' in 'kite'." },
            { kr: "ר", rom: "Resh", exp: "Guttural 'r', similar to French 'R'." },
            { kr: "ש", rom: "Shin / Sin", exp: "Like 'sh' (dot on right) or 's' (dot on left)." },
            { kr: "ת", rom: "Tav", exp: "Like 't' in 'top'." }
        ]
    },
    {
        id: "sofit_letters",
        label: "Final Letters (Sofit)",
        items: [
            { kr: "ך", rom: "Khaf Sofit", exp: "Final form of Khaf. Used only at the end of a word." },
            { kr: "ם", rom: "Mem Sofit", exp: "Final form of Mem." },
            { kr: "ן", rom: "Nun Sofit", exp: "Final form of Nun." },
            { kr: "ף", rom: "Fei Sofit", exp: "Final form of Fei." },
            { kr: "ץ", rom: "Tsadi Sofit", exp: "Final form of Tsadi." }
        ]
    },
    {
        id: "nikkud_vowels",
        label: "Basic Vowels (Nikkud)",
        items: [
            { kr: "אָ", rom: "Kamatz (a/o)", exp: "Usually 'a' as in 'father', sometimes 'o'." },
            { kr: "אַ", rom: "Patach (a)", exp: "Like 'a' in 'father'." },
            { kr: "אֵ", rom: "Tsere (e)", exp: "Like 'e' in 'they'." },
            { kr: "אֶ", rom: "Segol (e)", exp: "Like 'e' in 'pet'." },
            { kr: "אִ", rom: "Hirik (i)", exp: "Like 'ee' in 'see'." },
            { kr: "אוֹ", rom: "Holam (o)", exp: "Like 'o' in 'go'." },
            { kr: "אוּ", rom: "Shuruk (u)", exp: "Like 'oo' in 'boot'." },
            { kr: "אֻ", rom: "Kubutz (u)", exp: "Like 'oo' in 'boot'." }
        ]
    }
];

export const VOCABULARY = [
    { "it": "טוב", "en": "good", "type": "adjective", "category": "Adjectives", "topic": "Basics & Greetings" },
    { "it": "שלום", "en": "hello / peace", "type": "greeting", "category": "Basics", "topic": "Basics & Greetings" },
    { "it": "לא", "en": "no", "type": "adverb", "category": "Basics", "topic": "Basics & Greetings" },
    { "it": "תודה", "en": "thank you", "type": "greeting", "category": "Basics", "topic": "Basics & Greetings" },
    { "it": "כן", "en": "yes", "type": "adverb", "category": "Basics", "topic": "Basics & Greetings" },
    { "it": "ילד", "en": "boy", "type": "noun", "gender": "m", "category": "People", "topic": "People & Family" },
    { "it": "ילדה", "en": "girl", "type": "noun", "gender": "f", "category": "People", "topic": "People & Family" },
    { "it": "איש", "en": "man", "type": "noun", "gender": "m", "category": "People", "topic": "People & Family" },
    { "it": "אישה", "en": "woman", "type": "noun", "gender": "f", "category": "People", "topic": "People & Family" },
    { "it": "לחם", "en": "bread", "type": "noun", "gender": "m", "category": "Food & Drink", "topic": "Food & Drink" },
    { "it": "מים", "en": "water", "type": "noun", "gender": "m", "category": "Food & Drink", "topic": "Food & Drink" },
    { "it": "בית", "en": "house", "type": "noun", "gender": "m", "category": "Places", "topic": "House & Home" },
    { "it": "חתול", "en": "cat", "type": "noun", "gender": "m", "category": "Animals", "topic": "Nature & Animals" },
    { "it": "כלב", "en": "dog", "type": "noun", "gender": "m", "category": "Animals", "topic": "Nature & Animals" },
    { "it": "גדול", "en": "big", "type": "adjective", "category": "Adjectives", "topic": "Abstract Concepts" },
    { "it": "קטן", "en": "small", "type": "adjective", "category": "Adjectives", "topic": "Abstract Concepts" },
    { "it": "ספר", "en": "book", "type": "noun", "gender": "m", "category": "Objects", "topic": "Misc & Core Vocab" },
    { "it": "הוא", "en": "he", "type": "pronoun", "category": "Pronouns", "topic": "Misc & Core Vocab" },
    { "it": "אני", "en": "I", "type": "pronoun", "category": "Pronouns", "topic": "Misc & Core Vocab" },
    { "it": "היא", "en": "she", "type": "pronoun", "category": "Pronouns", "topic": "Misc & Core Vocab" },
    { "it": "אנחנו", "en": "we", "type": "pronoun", "category": "Pronouns", "topic": "Misc & Core Vocab" },
    { "it": "את", "en": "you (f.sg)", "type": "pronoun", "category": "Pronouns", "topic": "Misc & Core Vocab" },
    { "it": "אתה", "en": "you (m.sg)", "type": "pronoun", "category": "Pronouns", "topic": "Misc & Core Vocab" },
    { "he": "בְּבַקָּשָׁה", "rom": "bevakasha", "en": "please / you're welcome", "topic": "Basics & Greetings" },
    { "he": "סְלִיחָה", "rom": "slicha", "en": "excuse me / sorry", "topic": "Basics & Greetings" },
    { "he": "בּוֹקֶר טוֹב", "rom": "boker tov", "en": "good morning", "topic": "Basics & Greetings" },
    { "he": "עֶרֶב טוֹב", "rom": "erev tov", "en": "good evening", "topic": "Basics & Greetings" },
    { "he": "לַיְלָה טוֹב", "rom": "laila tov", "en": "good night", "topic": "Basics & Greetings" },
    { "he": "לְהִתְרָאוֹת", "rom": "lehitraot", "en": "goodbye", "topic": "Basics & Greetings" },
    { "he": "מָה שְׁלוֹמְךָ?", "rom": "ma shlomcha?", "en": "how are you? (m)", "topic": "Basics & Greetings" },
    { "he": "מָה שְׁלוֹמֵךְ?", "rom": "ma shlomech?", "en": "how are you? (f)", "topic": "Basics & Greetings" },
    { "he": "מִשְׁפָּחָה", "rom": "mishpacha", "en": "family", "topic": "People & Family" },
    { "he": "אַבָּא", "rom": "aba", "en": "father / dad", "topic": "People & Family" },
    { "he": "אִמָּא", "rom": "ima", "en": "mother / mom", "topic": "People & Family" },
    { "he": "אָח", "rom": "ach", "en": "brother", "topic": "People & Family" },
    { "he": "אָחוֹת", "rom": "achot", "en": "sister", "topic": "People & Family" },
    { "he": "סָבָּא", "rom": "saba", "en": "grandfather", "topic": "People & Family" },
    { "he": "סָבְתָא", "rom": "savta", "en": "grandmother", "topic": "People & Family" },
    { "he": "יֶלֶד", "rom": "yeled", "en": "boy / child", "topic": "People & Family" },
    { "he": "חָבֵר", "rom": "chaver", "en": "friend (m)", "topic": "People & Family" },
    { "he": "חֲבֵרָה", "rom": "chavera", "en": "friend (f)", "topic": "People & Family" },
    { "he": "אוֹכֶל", "rom": "ochel", "en": "food", "topic": "Food & Drink" },
    { "he": "חָלָב", "rom": "chalav", "en": "milk", "topic": "Food & Drink" },
    { "he": "קָפֶה", "rom": "cafe", "en": "coffee", "topic": "Food & Drink" },
    { "he": "תֵּה", "rom": "te", "en": "tea", "topic": "Food & Drink" },
    { "he": "בָּשָׂר", "rom": "basar", "en": "meat", "topic": "Food & Drink" },
    { "he": "דָּג", "rom": "dag", "en": "fish", "topic": "Food & Drink" },
    { "he": "פְּרִי", "rom": "pri", "en": "fruit", "topic": "Food & Drink" },
    { "he": "יֶרֶק", "rom": "yerek", "en": "vegetable", "topic": "Food & Drink" },
    { "he": "בֵּיצָה", "rom": "beitza", "en": "egg", "topic": "Food & Drink" },
    { "he": "מִסְעָדָה", "rom": "mis'ada", "en": "restaurant", "topic": "Food & Drink" },
    { "he": "חֶדֶר", "rom": "cheder", "en": "room", "topic": "House & Home" },
    { "he": "דֶּלֶת", "rom": "delet", "en": "door", "topic": "House & Home" },
    { "he": "חַלּוֹן", "rom": "chalon", "en": "window", "topic": "House & Home" },
    { "he": "מִטָּה", "rom": "mita", "en": "bed", "topic": "House & Home" },
    { "he": "שֻׁלְחָן", "rom": "shulchan", "en": "table", "topic": "House & Home" },
    { "he": "כִּסֵּא", "rom": "kise", "en": "chair", "topic": "House & Home" },
    { "he": "שֵׁרוּתִים", "rom": "sherutim", "en": "bathroom / toilet", "topic": "House & Home" },
    { "he": "זְמַן", "rom": "zman", "en": "time", "topic": "Time & Calendar" },
    { "he": "יוֹם", "rom": "yom", "en": "day", "topic": "Time & Calendar" },
    { "he": "שָׁבוּעַ", "rom": "shavua", "en": "week", "topic": "Time & Calendar" },
    { "he": "חוֹדֶשׁ", "rom": "chodesh", "en": "month", "topic": "Time & Calendar" },
    { "he": "שָׁנָה", "rom": "shana", "en": "year", "topic": "Time & Calendar" },
    { "he": "הַיּוֹם", "rom": "hayom", "en": "today", "topic": "Time & Calendar" },
    { "he": "מָחָר", "rom": "machar", "en": "tomorrow", "topic": "Time & Calendar" },
    { "he": "אֶתְמוֹל", "rom": "etmol", "en": "yesterday", "topic": "Time & Calendar" },
    { "he": "עַכְשָׁיו", "rom": "achshav", "en": "now", "topic": "Time & Calendar" },
    { "he": "עִיר", "rom": "ir", "en": "city", "topic": "City & Places" },
    { "he": "רְחוֹב", "rom": "rechov", "en": "street", "topic": "City & Places" },
    { "he": "בֵּית סֵפֶר", "rom": "beit sefer", "en": "school", "topic": "City & Places" },
    { "he": "עֲבוֹדָה", "rom": "avoda", "en": "work", "topic": "City & Places" },
    { "he": "חֲנוּת", "rom": "chanut", "en": "store / shop", "topic": "City & Places" },
    { "he": "אוֹטוֹבּוּס", "rom": "otobus", "en": "bus", "topic": "City & Places" },
    { "he": "רַכֶּבֶת", "rom": "rakevet", "en": "train", "topic": "City & Places" },
    { "he": "לָלֶכֶת", "rom": "lalechet", "en": "to go / walk", "topic": "Action Verbs" },
    { "he": "לַעֲשׂוֹת", "rom": "la'asot", "en": "to do / make", "topic": "Action Verbs" },
    { "he": "לֶאֱכוֹל", "rom": "le'echol", "en": "to eat", "topic": "Action Verbs" },
    { "he": "לִשְׁתּוֹת", "rom": "lishtot", "en": "to drink", "topic": "Action Verbs" },
    { "he": "לִרְאוֹת", "rom": "lir'ot", "en": "to see", "topic": "Action Verbs" },
    { "he": "לִשְׁמוֹעַ", "rom": "lishmoa", "en": "to hear", "topic": "Action Verbs" },
    { "he": "לְדַבֵּר", "rom": "ledaber", "en": "to speak", "topic": "Action Verbs" },
    { "he": "לִקְרוֹא", "rom": "likro", "en": "to read", "topic": "Action Verbs" },
    { "he": "לִכְתּוֹב", "rom": "lichtov", "en": "to write", "topic": "Action Verbs" },
    { "he": "לָדַעַת", "rom": "lada'at", "en": "to know", "topic": "Action Verbs" },
    { "he": "לַחְשׁוֹב", "rom": "lachshov", "en": "to think", "topic": "Action Verbs" },
    { "he": "רַע", "rom": "ra", "en": "bad", "topic": "Descriptive (Adjectives)" },
    { "he": "חָדָשׁ", "rom": "chadash", "en": "new", "topic": "Descriptive (Adjectives)" },
    { "he": "יָשָׁן", "rom": "yashan", "en": "old", "topic": "Descriptive (Adjectives)" },
    { "he": "יָפֶה", "rom": "yafe", "en": "beautiful / pretty", "topic": "Descriptive (Adjectives)" },
    { "he": "חַם", "rom": "cham", "en": "hot", "topic": "Descriptive (Adjectives)" },
    { "he": "קַר", "rom": "kar", "en": "cold", "topic": "Descriptive (Adjectives)" },
    { "he": "אֶפֶס", "rom": "efes", "en": "zero", "topic": "Numbers & Math" },
    { "he": "אַחַת", "rom": "achat", "en": "one", "topic": "Numbers & Math" },
    { "he": "שְׁתַּיִם", "rom": "shtayim", "en": "two", "topic": "Numbers & Math" },
    { "he": "שָׁלוֹשׁ", "rom": "shalosh", "en": "three", "topic": "Numbers & Math" },
    { "he": "אַרְבַּע", "rom": "arba", "en": "four", "topic": "Numbers & Math" },
    { "he": "חָמֵשׁ", "rom": "chamesh", "en": "five", "topic": "Numbers & Math" },
    { "he": "שֵׁשׁ", "rom": "shesh", "en": "six", "topic": "Numbers & Math" },
    { "he": "שֶׁבַע", "rom": "sheva", "en": "seven", "topic": "Numbers & Math" },
    { "he": "שְׁמוֹנֶה", "rom": "shmone", "en": "eight", "topic": "Numbers & Math" },
    { "he": "תֵּשַׁע", "rom": "tesha", "en": "nine", "topic": "Numbers & Math" },
    { "he": "עֶשֶׂר", "rom": "eser", "en": "ten", "topic": "Numbers & Math" },
    { "he": "עֶשְׂרִים", "rom": "esrim", "en": "twenty", "topic": "Numbers & Math" },
    { "he": "שְׁלוֹשִׁים", "rom": "shloshim", "en": "thirty", "topic": "Numbers & Math" },
    { "he": "אַרְבָּעִים", "rom": "arbaim", "en": "forty", "topic": "Numbers & Math" },
    { "he": "חֲמִשִּׁים", "rom": "chamishim", "en": "fifty", "topic": "Numbers & Math" },
    { "he": "מֵאָה", "rom": "mea", "en": "hundred", "topic": "Numbers & Math" },
    { "he": "אֶלֶף", "rom": "elef", "en": "thousand", "topic": "Numbers & Math" },
    { "he": "מִסְפָּר", "rom": "mispar", "en": "number", "topic": "Numbers & Math" },
    { "he": "צֶבַע", "rom": "tzeva", "en": "color", "topic": "Colors & Shapes" },
    { "he": "אָדוֹם", "rom": "adom", "en": "red", "topic": "Colors & Shapes" },
    { "he": "כָּחוֹל", "rom": "kachol", "en": "blue", "topic": "Colors & Shapes" },
    { "he": "יָרוֹק", "rom": "yarok", "en": "green", "topic": "Colors & Shapes" },
    { "he": "צָהוֹב", "rom": "tzahov", "en": "yellow", "topic": "Colors & Shapes" },
    { "he": "שָׁחוֹר", "rom": "shachor", "en": "black", "topic": "Colors & Shapes" },
    { "he": "לָבָן", "rom": "lavan", "en": "white", "topic": "Colors & Shapes" },
    { "he": "אָפוֹר", "rom": "afor", "en": "gray", "topic": "Colors & Shapes" },
    { "he": "חוּם", "rom": "chum", "en": "brown", "topic": "Colors & Shapes" },
    { "he": "וָרוֹד", "rom": "varod", "en": "pink", "topic": "Colors & Shapes" },
    { "he": "סָגוֹל", "rom": "sagol", "en": "purple", "topic": "Colors & Shapes" },
    { "he": "כָּתוֹם", "rom": "katom", "en": "orange", "topic": "Colors & Shapes" },
    { "he": "גּוּף", "rom": "guf", "en": "body", "topic": "Body & Anatomy" },
    { "he": "ראֹשׁ", "rom": "rosh", "en": "head", "topic": "Body & Anatomy" },
    { "he": "פָּנִים", "rom": "panim", "en": "face", "topic": "Body & Anatomy" },
    { "he": "עַיִן", "rom": "ayin", "en": "eye", "topic": "Body & Anatomy" },
    { "he": "אַף", "rom": "af", "en": "nose", "topic": "Body & Anatomy" },
    { "he": "פֶּה", "rom": "pe", "en": "mouth", "topic": "Body & Anatomy" },
    { "he": "אוֹזֶן", "rom": "ozen", "en": "ear", "topic": "Body & Anatomy" },
    { "he": "שֵׂעָר", "rom": "se'ar", "en": "hair", "topic": "Body & Anatomy" },
    { "he": "יָד", "rom": "yad", "en": "hand / arm", "topic": "Body & Anatomy" },
    { "he": "רֶגֶל", "rom": "regel", "en": "leg / foot", "topic": "Body & Anatomy" },
    { "he": "בֶּטֶן", "rom": "beten", "en": "stomach", "topic": "Body & Anatomy" },
    { "he": "גַּב", "rom": "gav", "en": "back", "topic": "Body & Anatomy" },
    { "he": "לֵב", "rom": "lev", "en": "heart", "topic": "Body & Anatomy" },
    { "he": "בֶּגֶד", "rom": "beged", "en": "clothes", "topic": "Clothing & Fashion" },
    { "he": "חוּלְצָה", "rom": "chultza", "en": "shirt", "topic": "Clothing & Fashion" },
    { "he": "מִכְנָסַיִם", "rom": "michnasayim", "en": "pants", "topic": "Clothing & Fashion" },
    { "he": "שִׂמְלָה", "rom": "simla", "en": "dress", "topic": "Clothing & Fashion" },
    { "he": "נַעֲלַיִם", "rom": "na'alayim", "en": "shoes", "topic": "Clothing & Fashion" },
    { "he": "גַּרְבַּיִם", "rom": "garbayim", "en": "socks", "topic": "Clothing & Fashion" },
    { "he": "מְעִיל", "rom": "me'il", "en": "coat / jacket", "topic": "Clothing & Fashion" },
    { "he": "כּוֹבַע", "rom": "kova", "en": "hat", "topic": "Clothing & Fashion" },
    { "he": "מְכוֹנִית", "rom": "mechonit", "en": "car", "topic": "Transportation" },
    { "he": "מָטוֹס", "rom": "matos", "en": "airplane", "topic": "Transportation" },
    { "he": "אוֹפַנַּיִם", "rom": "ofanayim", "en": "bicycle", "topic": "Transportation" },
    { "he": "סִירָה", "rom": "sira", "en": "boat", "topic": "Transportation" },
    { "he": "כַּרְטִיס", "rom": "kartis", "en": "ticket", "topic": "Transportation" },
    { "he": "תַּחֲנָה", "rom": "tachana", "en": "station", "topic": "Transportation" },
    { "he": "רוֹפֵא", "rom": "rofe", "en": "doctor", "topic": "Work & Professions" },
    { "he": "מוֹרֶה", "rom": "more", "en": "teacher", "topic": "Work & Professions" },
    { "he": "תַּלְמִיד", "rom": "talmid", "en": "student", "topic": "Work & Professions" },
    { "he": "שׁוֹטֵר", "rom": "shoter", "en": "police", "topic": "Work & Professions" },
    { "he": "מִשְׂרָד", "rom": "misrad", "en": "office", "topic": "Work & Professions" },
    { "he": "מְנַהֵל", "rom": "menahel", "en": "boss / manager", "topic": "Work & Professions" },
    { "he": "תַּפּוּחַ", "rom": "tapuach", "en": "apple", "topic": "Food & Drink" },
    { "he": "בָּנָנָה", "rom": "banana", "en": "banana", "topic": "Food & Drink" },
    { "עו": "עַגְבָנִיָּה", "rom": "agvaniya", "en": "tomato", "topic": "Food & Drink" },
    { "he": "מְלָפְפוֹן", "rom": "melafefon", "en": "cucumber", "topic": "Food & Drink" },
    { "he": "גְּבִינָה", "rom": "gvina", "en": "cheese", "topic": "Food & Drink" },
    { "he": "עוֹף", "rom": "of", "en": "chicken", "topic": "Food & Drink" },
    { "he": "מֶלַח", "rom": "melach", "en": "salt", "topic": "Food & Drink" },
    { "he": "סֻכָּר", "rom": "sukar", "en": "sugar", "topic": "Food & Drink" },
    { "he": "צִפּוֹר", "rom": "tzipor", "en": "bird", "topic": "Nature & Animals" },
    { "he": "סוּס", "rom": "sus", "en": "horse", "topic": "Nature & Animals" },
    { "he": "עֵץ", "rom": "etz", "en": "tree", "topic": "Nature & Animals" },
    { "he": "פֶּרַח", "rom": "perach", "en": "flower", "topic": "Nature & Animals" },
    { "he": "שֶׁמֶשׁ", "rom": "shemesh", "en": "sun", "topic": "Nature & Animals" },
    { "he": "יָרֵחַ", "rom": "yareach", "en": "moon", "topic": "Nature & Animals" },
    { "he": "שָׁמַיִם", "rom": "shamayim", "en": "sky", "topic": "Nature & Animals" },
    { "he": "יָם", "rom": "yam", "en": "sea", "topic": "Nature & Animals" },
    { "he": "שָׂמֵחַ", "rom": "sameach", "en": "happy", "topic": "Descriptive (Adjectives)" },
    { "he": "עָצוּב", "rom": "atzuv", "en": "sad", "topic": "Descriptive (Adjectives)" },
    { "he": "מַהֵר", "rom": "maher", "en": "fast", "topic": "Descriptive (Adjectives)" },
    { "he": "לְאַט", "rom": "le'at", "en": "slow", "topic": "Descriptive (Adjectives)" },
    { "he": "נָקִי", "rom": "naki", "en": "clean", "topic": "Descriptive (Adjectives)" },
    { "he": "מְלוּכְלָךְ", "rom": "meluchlach", "en": "dirty", "topic": "Descriptive (Adjectives)" },
    { "he": "יָקָר", "rom": "yakar", "en": "expensive / dear", "topic": "Descriptive (Adjectives)" },
    { "he": "זוֹל", "rom": "zol", "en": "cheap", "topic": "Descriptive (Adjectives)" },
    { "he": "קָשֶׁה", "rom": "kashe", "en": "hard / difficult", "topic": "Descriptive (Adjectives)" },
    { "he": "קַל", "rom": "kal", "en": "easy / light", "topic": "Descriptive (Adjectives)" },
    { "he": "לִקְנוֹת", "rom": "liknot", "en": "to buy", "topic": "Action Verbs" },
    { "he": "לִמְכּוֹר", "rom": "limkor", "en": "to sell", "topic": "Action Verbs" },
    { "he": "לָרוּץ", "rom": "larutz", "en": "to run", "topic": "Action Verbs" },
    { "he": "לִקְפּוֹץ", "rom": "likpotz", "en": "to jump", "topic": "Action Verbs" },
    { "he": "לִישׁוֹן", "rom": "lishon", "en": "to sleep", "topic": "Action Verbs" },
    { "he": "לָקוּם", "rom": "lakum", "en": "to get up / wake up", "topic": "Action Verbs" },
    { "he": "לְהָבִין", "rom": "lehavin", "en": "to understand", "topic": "Action Verbs" },
    { "he": "לִלְמוֹד", "rom": "lilmod", "en": "to learn / study", "topic": "Action Verbs" },
    { "he": "לִשְׁכּוֹחַ", "rom": "lishkoach", "en": "to forget", "topic": "Action Verbs" },
    { "he": "לִזְכּוֹר", "rom": "lizkor", "en": "to remember", "topic": "Action Verbs" },
    { "he": "מִטְבָּח", "rom": "mitbach", "en": "kitchen", "topic": "House & Home" },
    { "he": "סָלוֹן", "rom": "salon", "en": "living room", "topic": "House & Home" },
    { "he": "מִקְלַחַת", "rom": "miklachat", "en": "shower", "topic": "House & Home" },
    { "he": "מְקָרֵר", "rom": "mekarer", "en": "refrigerator", "topic": "House & Home" },
    { "he": "תַּנּוּר", "rom": "tanur", "en": "oven / heater", "topic": "House & Home" },
    { "he": "טֶלֶוִיזְיָה", "rom": "televizya", "en": "television", "topic": "House & Home" },
    { "he": "סַפָּה", "rom": "sapa", "en": "sofa / couch", "topic": "House & Home" },
    { "he": "אָרוֹן", "rom": "aron", "en": "closet / cabinet", "topic": "House & Home" },
    { "he": "מַפְתֵּחַ", "rom": "mafteach", "en": "key", "topic": "House & Home" },
    { "he": "גַּג", "rom": "gag", "en": "roof", "topic": "House & Home" },
    { "he": "קִיר", "rom": "kir", "en": "wall", "topic": "House & Home" },
    { "he": "רִצְפָּה", "rom": "ritzpa", "en": "floor", "topic": "House & Home" },
    { "he": "אֲרוּחַת בּוֹקֶר", "rom": "aruchat boker", "en": "breakfast", "topic": "Food & Drink" },
    { "he": "אֲרוּחַת צָהֳרַיִם", "rom": "aruchat tzohorayim", "en": "lunch", "topic": "Food & Drink" },
    { "he": "אֲרוּחַת עֶרֶב", "rom": "aruchat erev", "en": "dinner", "topic": "Food & Drink" },
    { "he": "קִנּוּחַ", "rom": "kinuach", "en": "dessert", "topic": "Food & Drink" },
    { "he": "תַּפּוּז", "rom": "tapuz", "en": "orange (fruit)", "topic": "Food & Drink" },
    { "he": "לִימוֹן", "rom": "limon", "en": "lemon", "topic": "Food & Drink" },
    { "he": "גֶּזֶר", "rom": "gezer", "en": "carrot", "topic": "Food & Drink" },
    { "he": "בָּצָל", "rom": "batzal", "en": "onion", "topic": "Food & Drink" },
    { "he": "שׁוּם", "rom": "shum", "en": "garlic", "topic": "Food & Drink" },
    { "he": "מָרָק", "rom": "marak", "en": "soup", "topic": "Food & Drink" },
    { "he": "סָלָט", "rom": "salat", "en": "salad", "topic": "Food & Drink" },
    { "he": "פַּסְטָה", "rom": "pasta", "en": "pasta", "topic": "Food & Drink" },
    { "he": "בִּירָה", "rom": "bira", "en": "beer", "topic": "Food & Drink" },
    { "he": "יַיִן", "rom": "yayin", "en": "wine", "topic": "Food & Drink" },
    { "he": "פַּארְק", "rom": "park", "en": "park", "topic": "City & Places" },
    { "he": "גִּנָּה", "rom": "gina", "en": "garden", "topic": "City & Places" },
    { "he": "חוֹף", "rom": "chof", "en": "beach", "topic": "City & Places" },
    { "he": "בֵּית קָפֶה", "rom": "beit cafe", "en": "cafe / coffee shop", "topic": "City & Places" },
    { "he": "בֵּית חוֹלִים", "rom": "beit cholim", "en": "hospital", "topic": "City & Places" },
    { "he": "בַּנְק", "rom": "bank", "en": "bank", "topic": "City & Places" },
    { "he": "בֵּית מִרְקַחַת", "rom": "beit mirkachat", "en": "pharmacy", "topic": "City & Places" },
    { "he": "מִשְׁטָרָה", "rom": "mishtara", "en": "police station", "topic": "City & Places" },
    { "he": "דּוֹאַר", "rom": "do'ar", "en": "post office", "topic": "City & Places" },
    { "he": "שְׂדֵה תְּעוּפָה", "rom": "sde te'ufa", "en": "airport", "topic": "City & Places" },
    { "he": "קַנְיוֹן", "rom": "kanyon", "en": "mall / shopping center", "topic": "City & Places" },
    { "he": "סוּפֶּרְמַרְקֶט", "rom": "supermarket", "en": "supermarket", "topic": "City & Places" },
    { "he": "מַשָּׂאִית", "rom": "masa'it", "en": "truck", "topic": "Transportation" },
    { "he": "מוֹנִית", "rom": "monit", "en": "taxi", "topic": "Transportation" },
    { "he": "רַכֶּבֶת תַּחְתִּית", "rom": "rakevet tachtit", "en": "subway", "topic": "Transportation" },
    { "he": "קַטְנוֹעַ", "rom": "katnoa", "en": "scooter / moped", "topic": "Transportation" },
    { "he": "רִשָּׁיוֹן", "rom": "rishayon", "en": "license", "topic": "Transportation" },
    { "he": "דֶּלֶק", "rom": "delek", "en": "fuel / gas", "topic": "Transportation" },
    { "he": "רַעֲיוֹן", "rom": "ra'ayon", "en": "idea", "topic": "Abstract Concepts" },
    { "he": "בְּעָיָה", "rom": "be'aya", "en": "problem", "topic": "Abstract Concepts" },
    { "he": "פִּתְרוֹן", "rom": "pitron", "en": "solution", "topic": "Abstract Concepts" },
    { "he": "שְׁאֵלָה", "rom": "she'ela", "en": "question", "topic": "Abstract Concepts" },
    { "he": "תְּשׁוּבָה", "rom": "tshuva", "en": "answer", "topic": "Abstract Concepts" },
    { "he": "אַהֲבָה", "rom": "ahava", "en": "love", "topic": "Abstract Concepts" },
    { "he": "תִּקְוָה", "rom": "tikva", "en": "hope", "topic": "Abstract Concepts" },
    { "he": "חֲלוֹם", "rom": "chalom", "en": "dream", "topic": "Abstract Concepts" },
    { "he": "סִיבָּה", "rom": "siba", "en": "reason / cause", "topic": "Abstract Concepts" },
    { "he": "הַצְלָחָה", "rom": "hatzlacha", "en": "success", "topic": "Abstract Concepts" },
    { "he": "טָעוּת", "rom": "ta'ut", "en": "mistake", "topic": "Abstract Concepts" },
    { "he": "סַכָּנָה", "rom": "sakana", "en": "danger", "topic": "Abstract Concepts" },
    { "he": "בְּטִיחוּת", "rom": "betichut", "en": "safety / security", "topic": "Abstract Concepts" },
    { "he": "אֱמֶת", "rom": "emet", "en": "truth", "topic": "Abstract Concepts" },
    { "he": "שֶׁקֶר", "rom": "sheker", "en": "lie / falsehood", "topic": "Abstract Concepts" },
    { "he": "לַעֲבוֹד", "rom": "la'avod", "en": "to work", "topic": "Action Verbs" },
    { "he": "לְשַׂחֵק", "rom": "lesachek", "en": "to play (a game)", "topic": "Action Verbs" },
    { "he": "לְנַגֵּן", "rom": "lenagen", "en": "to play (an instrument)", "topic": "Action Verbs" },
    { "he": "לָשִׁיר", "rom": "lashir", "en": "to sing", "topic": "Action Verbs" },
    { "he": "לִרְקוֹד", "rom": "lirkod", "en": "to dance", "topic": "Action Verbs" },
    { "he": "לִצְחוֹק", "rom": "litzchok", "en": "to laugh", "topic": "Action Verbs" },
    { "he": "לִבְכּוֹת", "rom": "livkot", "en": "to cry", "topic": "Action Verbs" },
    { "he": "לַעֲזוֹר", "rom": "la'azor", "en": "to help", "topic": "Action Verbs" },
    { "he": "לְבַקֵּשׁ", "rom": "levakesh", "en": "to ask / request", "topic": "Action Verbs" },
    { "he": "לִשְׁאוֹל", "rom": "lish'ol", "en": "to ask (a question)", "topic": "Action Verbs" },
    { "he": "לַעֲנוֹת", "rom": "la'anot", "en": "to answer", "topic": "Action Verbs" },
    { "he": "לְהַתְחִיל", "rom": "lehatchil", "en": "to start / begin", "topic": "Action Verbs" },
    { "he": "לְסַיֵּים", "rom": "lesayem", "en": "to finish", "topic": "Action Verbs" },
    { "he": "לַעֲצוֹר", "rom": "la'atzor", "en": "to stop", "topic": "Action Verbs" },
    { "he": "לְהַמְשִׁיךְ", "rom": "lehamshich", "en": "to continue", "topic": "Action Verbs" },
    { "he": "לַחְזוֹר", "rom": "lachzor", "en": "to return / come back", "topic": "Action Verbs" },
    { "he": "לָשִׂים", "rom": "lasim", "en": "to put", "topic": "Action Verbs" },
    { "he": "לָקַחַת", "rom": "lakachat", "en": "to take", "topic": "Action Verbs" },
    { "he": "לָתֵת", "rom": "latet", "en": "to give", "topic": "Action Verbs" },
    { "he": "לִמְצוֹא", "rom": "limtzo", "en": "to find", "topic": "Action Verbs" },
    { "he": "לְחַפֵּשׂ", "rom": "lechapes", "en": "to search / look for", "topic": "Action Verbs" },
    { "he": "לֶאֱהוֹב", "rom": "le'ehov", "en": "to love", "topic": "Action Verbs" },
    { "he": "אָרוֹךְ", "rom": "aroch", "en": "long", "topic": "Descriptive (Adjectives)" },
    { "he": "קָצָר", "rom": "katsar", "en": "short (length)", "topic": "Descriptive (Adjectives)" },
    { "he": "גָּבוֹהַּ", "rom": "gavoa", "en": "tall / high", "topic": "Descriptive (Adjectives)" },
    { "he": "נָמוּךְ", "rom": "namuch", "en": "short (height)", "topic": "Descriptive (Adjectives)" },
    { "he": "מָלֵא", "rom": "male", "en": "full", "topic": "Descriptive (Adjectives)" },
    { "he": "רֵיק", "rom": "rek", "en": "empty", "topic": "Descriptive (Adjectives)" },
    { "he": "פָּתוּחַ", "rom": "patuach", "en": "open", "topic": "Descriptive (Adjectives)" },
    { "he": "סָגוּר", "rom": "sagur", "en": "closed", "topic": "Descriptive (Adjectives)" },
    { "he": "חָזָק", "rom": "chazak", "en": "strong", "topic": "Descriptive (Adjectives)" },
    { "he": "חַלָּשׁ", "rom": "chalash", "en": "weak", "topic": "Descriptive (Adjectives)" },
    { "he": "עָשִׁיר", "rom": "ashir", "en": "rich", "topic": "Descriptive (Adjectives)" },
    { "he": "עָנִי", "rom": "ani", "en": "poor", "topic": "Descriptive (Adjectives)" },
    { "he": "חָכָם", "rom": "chacham", "en": "smart / wise", "topic": "Descriptive (Adjectives)" },
    { "he": "טִפֵּשׁ", "rom": "tipesh", "en": "stupid", "topic": "Descriptive (Adjectives)" },
    { "he": "מְעַנְיֵן", "rom": "me'anyen", "en": "interesting", "topic": "Descriptive (Adjectives)" },
    { "he": "מְשַׁעֲמֵם", "rom": "mesha'amem", "en": "boring", "topic": "Descriptive (Adjectives)" },
    { "he": "חָשׁוּב", "rom": "chashuv", "en": "important", "topic": "Descriptive (Adjectives)" },
    { "he": "מוּזָר", "rom": "muzar", "en": "weird / strange", "topic": "Descriptive (Adjectives)" },
    { "he": "מַצְחִיק", "rom": "matzchik", "en": "funny", "topic": "Descriptive (Adjectives)" },
    { "he": "הַר", "rom": "har", "en": "mountain", "topic": "Nature & Animals" },
    { "he": "נָהָר", "rom": "nahar", "en": "river", "topic": "Nature & Animals" },
    { "he": "אֲגַם", "rom": "agam", "en": "lake", "topic": "Nature & Animals" },
    { "he": "חוֹל", "rom": "chol", "en": "sand", "topic": "Nature & Animals" },
    { "he": "אֶבֶן", "rom": "even", "en": "stone / rock", "topic": "Nature & Animals" },
    { "he": "עָנָן", "rom": "anan", "en": "cloud", "topic": "Nature & Animals" },
    { "he": "גֶּשֶׁם", "rom": "geshem", "en": "rain", "topic": "Nature & Animals" },
    { "he": "רוּחַ", "rom": "ruach", "en": "wind / spirit", "topic": "Nature & Animals" },
    { "he": "שֶׁלֶג", "rom": "sheleg", "en": "snow", "topic": "Nature & Animals" },
    { "he": "פָּרָה", "rom": "para", "en": "cow", "topic": "Nature & Animals" },
    { "he": "כִּבְשָׂה", "rom": "kivsa", "en": "sheep", "topic": "Nature & Animals" },
    { "he": "חֲזִיר", "rom": "chazir", "en": "pig", "topic": "Nature & Animals" },
    { "he": "אַרְיֵה", "rom": "arye", "en": "lion", "topic": "Nature & Animals" },
    { "he": "דּוֹב", "rom": "dov", "en": "bear", "topic": "Nature & Animals" },
    { "he": "קוֹף", "rom": "kof", "en": "monkey", "topic": "Nature & Animals" },
    { "he": "נָחָשׁ", "rom": "nachash", "en": "snake", "topic": "Nature & Animals" },
    { "he": "תַּרְנְגוֹל", "rom": "tarnegol", "en": "rooster", "topic": "Nature & Animals" },
    { "he": "עַכְבָּר", "rom": "achbar", "en": "mouse", "topic": "Nature & Animals" }
];

export const CONJUGATIONS = [
    {
        verb: "לאכול (le'echol)",
        en: "to eat",
        tense: "Present (Pa'al)",
        forms: [
            { pronoun: "m.sg (אני/אתה/הוא)", form: "אוכל (ochel)" },
            { pronoun: "f.sg (אני/את/היא)", form: "אוכלת (ochelet)" },
            { pronoun: "m.pl (אנחנו/אתם/הם)", form: "אוכלים (ochlim)" },
            { pronoun: "f.pl (אנחנו/אתן/הן)", form: "אוכלות (ochlot)" }
        ]
    },
    {
        verb: "לדבר (ledaber)",
        en: "to speak",
        tense: "Present (Pi'el)",
        forms: [
            { pronoun: "m.sg", form: "מדבר (medaber)" },
            { pronoun: "f.sg", form: "מדברת (medaberet)" },
            { pronoun: "m.pl", form: "מדברים (medabrim)" },
            { pronoun: "f.pl", form: "מדברות (medabrot)" }
        ]
    },
    {
        verb: "להרגיש (lehargish)",
        en: "to feel",
        tense: "Present (Hif'il)",
        forms: [
            { pronoun: "m.sg", form: "מרגיש (margish)" },
            { pronoun: "f.sg", form: "מרגישה (margisha)" },
            { pronoun: "m.pl", form: "מרגישים (margishim)" },
            { pronoun: "f.pl", form: "מרגישות (margishot)" }
        ]
    }
];

export const GRAMMAR_QUESTIONS = [
    {
        sentence: "אני קורא ספר.",
        en: "I (m) am reading a book.",
        question: "Why is 'קורא' (kore) used here instead of 'קוראת' (koret)?",
        options: [
            "Because the speaker is male (masculine singular).",
            "Because 'book' is masculine.",
            "Because it is in the past tense.",
            "Because it is a plural subject."
        ],
        answer: "Because the speaker is male (masculine singular).",
        explanation: "In Hebrew present tense, verbs conjugate based on the gender and number of the subject. 'קורא' is the masculine singular form of 'to read'."
    },
    {
        sentence: "הילדה היפה הולכת לבית הספר.",
        en: "The beautiful girl goes to the school.",
        question: "How does the adjective 'יפה' (beautiful) agree with the noun 'ילדה' (girl)?",
        options: [
            "It matches in gender (feminine), number (singular), and definiteness (has 'ה').",
            "It only matches in gender.",
            "Adjectives don't change form in Hebrew.",
            "It takes the prefix 'ל'."
        ],
        answer: "It matches in gender (feminine), number (singular), and definiteness (has 'ה').",
        explanation: "In Hebrew, adjectives follow the noun and must agree in gender, number, and definiteness. Since it's 'THE girl' (הילדה), it must be 'THE beautiful' (היפה)."
    }
];

export const IDIOMS = [
    {
        phrase: "על הפנים",
        literal: "On the face",
        meaning: "Terrible, awful, feeling very bad.",
        usage: "Used to describe a bad situation or feeling sick.",
        example: "איך היה המבחן? - על הפנים.",
        category: "Emotions"
    },
    {
        phrase: "חבל על הזמן",
        literal: "Pity on the time",
        meaning: "Amazing, fantastic (slang context).",
        usage: "Ironically, in modern slang, it means something is incredibly good (so good it's a waste of time to describe it).",
        example: "המסעדה הזאת פשוט חבל על הזמן!",
        category: "Slang"
    },
    {
        phrase: "חי בסרט",
        literal: "Lives in a movie",
        meaning: "Delusional, unrealistic.",
        usage: "Said about someone who is completely out of touch with reality.",
        example: "הוא חושב שהוא יתעשר מחר. ממש חי בסרט.",
        category: "Character"
    }
];

export const SENTENCE_BUILD_PROMPTS = [
    { prompt: "Introduce yourself (name, age, where you from).", en_hint: "קוראים לי... אני בן/בת... אני מ...", topic: "introductions" },
    { prompt: "Order a coffee and a pastry at a cafe.", en_hint: "אפשר בבקשה קפה ו...", topic: "food & drink" },
    { prompt: "Ask someone how they are doing today.", en_hint: "מה שלומך היום?", topic: "greetings" }
];

export const CONVERSATION_TOPICS = [
    "Introducing yourself and meeting new people",
    "Ordering food at a market (Shuk)",
    "Talking about the weekend (Shabbat)",
    "Asking for directions in Tel Aviv",
    "Discussing hobbies and sports",
    "Talking about your family"
];

export const VIDEOS = [
    {
        id: "jvDCEXbxxL0",
        title: "Learn Hebrew in 25 Minutes - ALL the Basics You Need",
        channel: "Learn Hebrew with HebrewPod101.com",
        thumbnail: "https://img.youtube.com/vi/jvDCEXbxxL0/mqdefault.jpg"
    },
    {
        id: "Ekc3lIVdHEU",
        title: "Lesson 1: The Hebrew Alphabet | Crash Course in Hebrew Reading & Pronunciation",
        channel: "The WORD in HEBREW",
        thumbnail: "https://img.youtube.com/vi/Ekc3lIVdHEU/mqdefault.jpg"
    },
    {
        id: "UMdr0bhgUw8",
        title: "Learn Hebrew Today - ALL the Hebrew Basics for Beginners",
        channel: "Learn Hebrew with HebrewPod101.com",
        thumbnail: "https://img.youtube.com/vi/UMdr0bhgUw8/mqdefault.jpg"
    },
    {
        id: "SlvEOlbK7Uw",
        title: "Hebrew Greetings for Beginners - Basic Phrases You Need to Know | Lesson from the Online Course",
        channel: "The Complete Hebrew Course For Beginners",
        thumbnail: "https://img.youtube.com/vi/SlvEOlbK7Uw/mqdefault.jpg"
    }
];

export const CULTURE = [
    {
        "id": "nMQw29nfzpg",
        "title": "Omer Adam - Tel Aviv (עומר אדם - תל אביב)",
        "channel": "עומר אדם - הערוץ הרשמי",
        "thumbnail": "https://img.youtube.com/vi/nMQw29nfzpg/mqdefault.jpg",
        "category": "Music"
    },
    {
        "id": "Y0KxZz5k-RE",
        "title": "Shlomo Artzi - Teta'aru Lachem (שלמה ארצי - תתארו לכם)",
        "channel": "Shlomo Artzi",
        "thumbnail": "https://img.youtube.com/vi/Y0KxZz5k-RE/mqdefault.jpg",
        "category": "Music"
    },
    {
        "id": "mjmMllp8hJg",
        "title": "Naomi Shemer - Yerushalayim Shel Zahav (ירושלים של זהב)",
        "channel": "Israel Classics",
        "thumbnail": "https://img.youtube.com/vi/mjmMllp8hJg/mqdefault.jpg",
        "category": "Music"
    },
    {
        "id": "sMEyfEoKQr0",
        "title": "Hatikva 6 - Hachi Israelit (התקווה 6 - הכי ישראלי)",
        "channel": "Hatikva 6",
        "thumbnail": "https://img.youtube.com/vi/sMEyfEoKQr0/mqdefault.jpg",
        "category": "Music"
    },
    {
        "id": "Kp6p8HKB0T0",
        "title": "Shtisel - Official Trailer (English Subs)",
        "channel": "yes Studios",
        "thumbnail": "https://img.youtube.com/vi/Kp6p8HKB0T0/mqdefault.jpg",
        "category": "TV Show"
    },
    {
        "id": "eawzxNEWqE4",
        "title": "Fauda | Official Trailer",
        "channel": "Netflix",
        "thumbnail": "https://img.youtube.com/vi/eawzxNEWqE4/mqdefault.jpg",
        "category": "TV Show"
    },
    {
        "id": "Z4VGuU5OHns",
        "title": "The Lesson | Israeli Best Drama Series",
        "channel": "ChaiFlicks",
        "thumbnail": "https://img.youtube.com/vi/Z4VGuU5OHns/mqdefault.jpg",
        "category": "TV Show"
    },
    {
        "id": "ylzO9vbEpPg",
        "title": "Waltz with Bashir (2008) - Official Trailer",
        "channel": "Sony Pictures",
        "thumbnail": "https://img.youtube.com/vi/ylzO9vbEpPg/mqdefault.jpg",
        "category": "Movie"
    },
    {
        "id": "l9w_XgNlsTo",
        "title": "Zero Motivation (אפס ביחסי אנוש) - Trailer",
        "channel": "Kino Lorber",
        "thumbnail": "https://img.youtube.com/vi/l9w_XgNlsTo/mqdefault.jpg",
        "category": "Movie"
    }
];

export const PROGRESSION = [
    "Basics & Greetings",
    "Descriptive (Adjectives)",
    "People & Family",
    "Action Verbs",
    "Numbers & Math",
    "Time & Calendar",
    "Food & Drink",
    "House & Home",
    "City & Places",
    "Transportation",
    "Body & Anatomy",
    "Clothing & Fashion",
    "Colors & Shapes",
    "Nature & Animals",
    "Work & Professions",
    "Abstract Concepts",
    "Misc & Core Vocab"
];
