export const VOCABULARY = [
  {"pt":"olá","rom":"o-la","en":"hello","topic":"Basics & Greetings"},
  {"pt":"obrigado","rom":"o-bri-ga-do","en":"thank you","topic":"Basics & Greetings"},
  {"pt":"sim","rom":"sim","en":"yes","topic":"Basics & Greetings"},
  {"pt":"não","rom":"nao","en":"no","topic":"Basics & Greetings"},
  {"pt":"maçã","rom":"ma-sa","en":"apple","topic":"Food & Drink"},
  {"pt":"água","rom":"a-gua","en":"water","topic":"Food & Drink"},
  {"pt":"gato","rom":"ga-to","en":"cat","topic":"Nature & Animals"},
  {"pt":"cachorro","rom":"ca-chor-ro","en":"dog","topic":"Nature & Animals"},
  {"pt":"por favor","en":"please","topic":"Basics & Greetings"},
  {"pt":"com licença","en":"excuse me","topic":"Basics & Greetings"},
  {"pt":"bom dia","en":"good morning","topic":"Basics & Greetings"},
  {"pt":"boa noite","en":"good night","topic":"Basics & Greetings"},
  {"pt":"família","en":"family","topic":"People & Family"},
  {"pt":"mãe","en":"mother","topic":"People & Family"},
  {"pt":"pai","en":"father","topic":"People & Family"},
  {"pt":"amigo","en":"friend","topic":"People & Family"},
  {"pt":"pessoa","en":"person","topic":"People & Family"},
  {"pt":"homem","en":"man","topic":"People & Family"},
  {"pt":"mulher","en":"woman","topic":"People & Family"},
  {"pt":"criança","en":"child","topic":"People & Family"},
  {"pt":"pais","en":"parents","topic":"People & Family"},
  {"pt":"irmão","en":"brother","topic":"People & Family"},
  {"pt":"irmã","en":"sister","topic":"People & Family"},
  {"pt":"avô","en":"grandfather","topic":"People & Family"},
  {"pt":"avó","en":"grandmother","topic":"People & Family"},
  {"pt":"tempo","en":"time","topic":"Time & Calendar"},
  {"pt":"hoje","en":"today","topic":"Time & Calendar"},
  {"pt":"amanhã","en":"tomorrow","topic":"Time & Calendar"},
  {"pt":"ontem","en":"yesterday","topic":"Time & Calendar"},
  {"pt":"dia","en":"day","topic":"Time & Calendar"},
  {"pt":"semana","en":"week","topic":"Time & Calendar"},
  {"pt":"mês","en":"month","topic":"Time & Calendar"},
  {"pt":"ano","en":"year","topic":"Time & Calendar"},
  {"pt":"manhã","en":"morning","topic":"Time & Calendar"},
  {"pt":"tarde","en":"afternoon","topic":"Time & Calendar"},
  {"pt":"início da noite","en":"evening","topic":"Time & Calendar"},
  {"pt":"noite","en":"night","topic":"Time & Calendar"},
  {"pt":"sempre","en":"always","topic":"Time & Calendar"},
  {"pt":"nunca","en":"never","topic":"Time & Calendar"},
  {"pt":"agora","en":"now","topic":"Time & Calendar"},
  {"pt":"comida","en":"food","topic":"Food & Drink"},
  {"pt":"pão","en":"bread","topic":"Food & Drink"},
  {"pt":"carne","en":"meat","topic":"Food & Drink"},
  {"pt":"peixe","en":"fish","topic":"Food & Drink"},
  {"pt":"queijo","en":"cheese","topic":"Food & Drink"},
  {"pt":"vegetal","en":"vegetable","topic":"Food & Drink"},
  {"pt":"fruta","en":"fruit","topic":"Food & Drink"},
  {"pt":"café","en":"coffee","topic":"Food & Drink"},
  {"pt":"chá","en":"tea","topic":"Food & Drink"},
  {"pt":"leite","en":"milk","topic":"Food & Drink"},
  {"pt":"cerveja","en":"beer","topic":"Food & Drink"},
  {"pt":"vinho","en":"wine","topic":"Food & Drink"},
  {"pt":"café da manhã","en":"breakfast","topic":"Food & Drink"},
  {"pt":"almoço","en":"lunch","topic":"Food & Drink"},
  {"pt":"jantar","en":"dinner","topic":"Food & Drink"},
  {"pt":"casa","en":"house","topic":"House & Home"},
  {"pt":"quarto","en":"room","topic":"House & Home"},
  {"pt":"porta","en":"door","topic":"House & Home"},
  {"pt":"janela","en":"window","topic":"House & Home"},
  {"pt":"cama","en":"bed","topic":"House & Home"},
  {"pt":"mesa","en":"table","topic":"House & Home"},
  {"pt":"cadeira","en":"chair","topic":"House & Home"},
  {"pt":"cozinha","en":"kitchen","topic":"House & Home"},
  {"pt":"banheiro","en":"bathroom","topic":"House & Home"},
  {"pt":"pássaro","en":"bird","topic":"Nature & Animals"},
  {"pt":"árvore","en":"tree","topic":"Nature & Animals"},
  {"pt":"sol","en":"sun","topic":"Nature & Animals"},
  {"pt":"lua","en":"moon","topic":"Nature & Animals"},
  {"pt":"flor","en":"flower","topic":"Nature & Animals"},
  {"pt":"céu","en":"sky","topic":"Nature & Animals"},
  {"pt":"mar","en":"sea","topic":"Nature & Animals"},
  {"pt":"montanha","en":"mountain","topic":"Nature & Animals"},
  {"pt":"cidade","en":"city","topic":"City & Places"},
  {"pt":"rua","en":"street","topic":"City & Places"},
  {"pt":"escola","en":"school","topic":"City & Places"},
  {"pt":"hospital","en":"hospital","topic":"City & Places"},
  {"pt":"loja","en":"store","topic":"City & Places"},
  {"pt":"restaurante","en":"restaurant","topic":"City & Places"},
  {"pt":"estação","en":"station","topic":"City & Places"},
  {"pt":"parque","en":"park","topic":"City & Places"},
  {"pt":"carro","en":"car","topic":"Transportation"},
  {"pt":"ônibus","en":"bus","topic":"Transportation"},
  {"pt":"trem","en":"train","topic":"Transportation"},
  {"pt":"avião","en":"airplane","topic":"Transportation"},
  {"pt":"barco","en":"boat","topic":"Transportation"},
  {"pt":"ser","en":"to be (permanent)","topic":"Action Verbs"},
  {"pt":"estar","en":"to be (temporary)","topic":"Action Verbs"},
  {"pt":"ter","en":"to have","topic":"Action Verbs"},
  {"pt":"fazer","en":"to do / to make","topic":"Action Verbs"},
  {"pt":"ir","en":"to go","topic":"Action Verbs"},
  {"pt":"vir","en":"to come","topic":"Action Verbs"},
  {"pt":"ver","en":"to see","topic":"Action Verbs"},
  {"pt":"falar","en":"to speak","topic":"Action Verbs"},
  {"pt":"comer","en":"to eat","topic":"Action Verbs"},
  {"pt":"beber","en":"to drink","topic":"Action Verbs"},
  {"pt":"dormir","en":"to sleep","topic":"Action Verbs"},
  {"pt":"escrever","en":"to write","topic":"Action Verbs"},
  {"pt":"ler","en":"to read","topic":"Action Verbs"},
  {"pt":"caminhar","en":"to walk","topic":"Action Verbs"},
  {"pt":"correr","en":"to run","topic":"Action Verbs"},
  {"pt":"comprar","en":"to buy","topic":"Action Verbs"},
  {"pt":"vender","en":"to sell","topic":"Action Verbs"},
  {"pt":"entender","en":"to understand","topic":"Action Verbs"},
  {"pt":"saber","en":"to know (a fact)","topic":"Action Verbs"},
  {"pt":"bom","en":"good","topic":"Descriptive (Adjectives)"},
  {"pt":"mau","en":"bad","topic":"Descriptive (Adjectives)"},
  {"pt":"grande","en":"big","topic":"Descriptive (Adjectives)"},
  {"pt":"pequeno","en":"small","topic":"Descriptive (Adjectives)"},
  {"pt":"quente","en":"hot","topic":"Descriptive (Adjectives)"},
  {"pt":"frio","en":"cold","topic":"Descriptive (Adjectives)"},
  {"pt":"novo","en":"new","topic":"Descriptive (Adjectives)"},
  {"pt":"velho","en":"old","topic":"Descriptive (Adjectives)"},
  {"pt":"bonito","en":"beautiful","topic":"Descriptive (Adjectives)"},
  {"pt":"rápido","en":"fast","topic":"Descriptive (Adjectives)"},
  {"pt":"lento","en":"slow","topic":"Descriptive (Adjectives)"},
  {"pt":"feliz","en":"happy","topic":"Descriptive (Adjectives)"},
  {"pt":"triste","en":"sad","topic":"Descriptive (Adjectives)"},
  {"pt":"vermelho","en":"red","topic":"Colors & Shapes"},
  {"pt":"azul","en":"blue","topic":"Colors & Shapes"},
  {"pt":"verde","en":"green","topic":"Colors & Shapes"},
  {"pt":"amarelo","en":"yellow","topic":"Colors & Shapes"},
  {"pt":"preto","en":"black","topic":"Colors & Shapes"},
  {"pt":"branco","en":"white","topic":"Colors & Shapes"},
  {"pt":"um","en":"one","topic":"Numbers & Math"},
  {"pt":"dois","en":"two","topic":"Numbers & Math"},
  {"pt":"três","en":"three","topic":"Numbers & Math"},
  {"pt":"quatro","en":"four","topic":"Numbers & Math"},
  {"pt":"cinco","en":"five","topic":"Numbers & Math"},
  {"pt":"seis","en":"six","topic":"Numbers & Math"},
  {"pt":"sete","en":"seven","topic":"Numbers & Math"},
  {"pt":"oito","en":"eight","topic":"Numbers & Math"},
  {"pt":"nove","en":"nine","topic":"Numbers & Math"},
  {"pt":"dez","en":"ten","topic":"Numbers & Math"},
  {"pt":"livro","en":"book","topic":"Misc & Core Vocab"},
  {"pt":"caneta","en":"pen","topic":"Misc & Core Vocab"},
  {"pt":"dinheiro","en":"money","topic":"Misc & Core Vocab"},
  {"pt":"amor","en":"love","topic":"Abstract Concepts"},
  {"pt":"mundo","en":"world","topic":"Abstract Concepts"},
  {"pt":"vida","en":"life","topic":"Abstract Concepts"}
];

export const CONJUGATIONS = [];
export const GRAMMAR_QUESTIONS = [
    {
        sentence: "Eu sou estudante.",
        en: "I am a student.",
        question: "Why do we use 'sou' instead of 'estou' here?",
        options: [
            "'Sou' is used for temporary states.",
            "'Sou' is from the verb 'ser', used for permanent characteristics like professions.",
            "'Estou' is only used for locations.",
            "They are interchangeable."
        ],
        answer: 1,
        explanation: "Portuguese has two verbs for 'to be': 'ser' (permanent/identity) and 'estar' (temporary/location). Being a student is treated as an identity/profession, so 'ser' (sou) is used."
    }
];
export const IDIOMS = [
    {"phrase":"Pão, pão, queijo, queijo","literal":"Bread, bread, cheese, cheese","meaning":"To call a spade a spade / to tell it like it is","usage":"Used when speaking plainly and directly.","example":"Comigo é assim: pão, pão, queijo, queijo.","category":"Communication"},
    {"phrase":"Falar pelos cotovelos","literal":"To speak through the elbows","meaning":"To talk someone's ear off / to talk too much","usage":"When someone is constantly talking without stopping.","example":"A vizinha fala pelos cotovelos!","category":"Social Life"},
    {"phrase":"Chorar sobre o leite derramado","literal":"To cry over spilled milk","meaning":"To cry over spilled milk","usage":"Used to say there's no point in being sad over something that can't be undone.","example":"Não adianta chorar sobre o leite derramado, vamos focar no futuro.","category":"Emotions"},
    {"phrase":"Dar com os burros n'água","literal":"To give with the donkeys in the water","meaning":"To fail spectacularly / to hit a dead end","usage":"When a plan goes wrong.","example":"Ele tentou enganar o chefe, mas deu com os burros n'água.","category":"Frustration"},
    {"phrase":"Custar os olhos da cara","literal":"To cost the eyes of the face","meaning":"To cost an arm and a leg","usage":"To complain about a very high price.","example":"Esse computador novo custou os olhos da cara.","category":"Money"},
    {"phrase":"Procurar chifre em cabeça de cavalo","literal":"To look for a horn on a horse's head","meaning":"To look for problems where there are none / overcomplicate","usage":"When someone is being overly suspicious or paranoid.","example":"Você está procurando chifre em cabeça de cavalo, não há conspiração nenhuma.","category":"Personality & Mind"},
    {"phrase":"Estar com a pulga atrás da orelha","literal":"To be with the flea behind the ear","meaning":"To be suspicious / to smell a rat","usage":"When you suspect something is wrong.","example":"Fiquei com a pulga atrás da orelha depois dessa ligação.","category":"Emotions"},
    {"phrase":"Lavar as mãos","literal":"To wash the hands","meaning":"To wash one's hands of the matter","usage":"To abdicate responsibility for a situation.","example":"Eu avisei que daria errado. Agora, eu lavo as minhas mãos.","category":"Work & Business"},
    {"phrase":"Chutar o balde","literal":"To kick the bucket","meaning":"To lose one's temper / give up completely","usage":"Note: Unlike in English, this does NOT mean 'to die'. It means to throw a fit or abandon a task in frustration.","example":"Fiquei tão irritado com o projeto que quase chutei o balde.","category":"Anger"},
    {"phrase":"Bater as botas","literal":"To hit the boots","meaning":"To kick the bucket / to die","usage":"A colloquial, slightly irreverent way to say someone died.","example":"Infelizmente, o cachorro do vizinho bateu as botas.","category":"Food & Daily Life"},
    {"phrase":"Olá, como você está?","meaning":"Hello, how are you?","category":"Conversational"},
    {"phrase":"Estou ótimo, obrigado.","meaning":"I am doing great, thank you.","category":"Conversational"},
    {"phrase":"Como você se chama?","meaning":"What is your name?","category":"Conversational"},
    {"phrase":"Meu nome é...","meaning":"My name is...","category":"Conversational"},
    {"phrase":"Prazer em conhecer você.","meaning":"Nice to meet you.","category":"Conversational"},
    {"phrase":"De onde você é?","meaning":"Where are you from?","category":"Conversational"},
    {"phrase":"Eu sou de...","meaning":"I am from...","category":"Conversational"},
    {"phrase":"Você fala inglês?","meaning":"Do you speak English?","category":"Conversational"},
    {"phrase":"Eu falo um pouco.","meaning":"I speak a little bit.","category":"Conversational"},
    {"phrase":"Não entendo.","meaning":"I don't understand.","category":"Conversational"},
    {"phrase":"Você pode falar mais devagar, por favor?","meaning":"Can you speak more slowly, please?","category":"Conversational"},
    {"phrase":"Você pode repetir isso?","meaning":"Can you repeat that?","category":"Conversational"},
    {"phrase":"Com licença, onde fica o banheiro?","meaning":"Excuse me, where is the bathroom?","category":"Conversational"},
    {"phrase":"Quanto custa isso?","meaning":"How much does this cost?","category":"Conversational"},
    {"phrase":"Eu gostaria de fazer o pedido.","meaning":"I would like to order.","category":"Conversational"},
    {"phrase":"A conta, por favor.","meaning":"The check, please.","category":"Conversational"},
    {"phrase":"Posso pagar com cartão de crédito?","meaning":"Can I pay with a credit card?","category":"Conversational"},
    {"phrase":"Que horas são?","meaning":"What time is it?","category":"Conversational"},
    {"phrase":"Preciso de ajuda, por favor.","meaning":"I need some help, please.","category":"Conversational"},
    {"phrase":"Estou perdido.","meaning":"I am lost.","category":"Conversational"},
    {"phrase":"Tenha um ótimo dia!","meaning":"Have a great day!","category":"Conversational"},
    {"phrase":"Eu amo aprender idiomas.","meaning":"I love learning languages.","category":"Conversational"},
    {"phrase":"O que você vai fazer neste fim de semana?","meaning":"What are you doing this weekend?","category":"Conversational"},
    {"phrase":"Estou me sentindo um pouco cansado.","meaning":"I am feeling a bit tired.","category":"Conversational"},
    {"phrase":"Você está com fome?","meaning":"Are you hungry?","category":"Conversational"},
    {"phrase":"Isso é muito gostoso.","meaning":"This is very delicious.","category":"Conversational"},
    {"phrase":"Eu te ligo mais tarde.","meaning":"I will call you later.","category":"Conversational"},
    {"phrase":"Qual é a sua comida favorita?","meaning":"What is your favorite food?","category":"Conversational"},
    {"phrase":"Como está o tempo hoje?","meaning":"How is the weather today?","category":"Conversational"},
    {"phrase":"Desculpe, estou atrasado.","meaning":"I am sorry, I am late.","category":"Conversational"}
];
export const CONVERSATION_TOPICS = [
    "Teus passatempos (Your hobbies)",
    "Comida favorita (Favorite food)",
    "Planos para o futuro (Plans for the future)"
];
export const SENTENCE_BUILD_PROMPTS = [
    { prompt: "Describe what you did this morning.", en_hint: "Use the Pretérito Perfeito.", topic: "daily routine" }
];
export const VIDEOS = [];
export const CULTURE = [];

export const PROGRESSION = [
    "Basics & Greetings",
    "Food & Drink",
    "Nature & Animals",
    "Numbers & Math",
    "Time & Calendar",
    "Action Verbs",
    "Descriptive (Adjectives)",
    "People & Family",
    "House & Home",
    "City & Places",
    "Transportation",
    "Abstract Concepts",
    "Misc & Core Vocab"
];
