export const VOCABULARY = [
  {"ru":"привет","rom":"privet","en":"hello","topic":"Basics & Greetings"},
  {"ru":"спасибо","rom":"spasibo","en":"thank you","topic":"Basics & Greetings"},
  {"ru":"да","rom":"da","en":"yes","topic":"Basics & Greetings"},
  {"ru":"нет","rom":"net","en":"no","topic":"Basics & Greetings"},
  {"ru":"яблоко","rom":"yabloko","en":"apple","topic":"Food & Drink"},
  {"ru":"вода","rom":"voda","en":"water","topic":"Food & Drink"},
  {"ru":"кот","rom":"kot","en":"cat","topic":"Nature & Animals"},
  {"ru":"собака","rom":"sobaka","en":"dog","topic":"Nature & Animals"},
  {"ru":"пожалуйста","en":"please","topic":"Basics & Greetings"},
  {"ru":"извините","en":"excuse me","topic":"Basics & Greetings"},
  {"ru":"доброе утро","en":"good morning","topic":"Basics & Greetings"},
  {"ru":"спокойной ночи","en":"good night","topic":"Basics & Greetings"},
  {"ru":"семья","en":"family","topic":"People & Family"},
  {"ru":"мать","en":"mother","topic":"People & Family"},
  {"ru":"отец","en":"father","topic":"People & Family"},
  {"ru":"друг","en":"friend","topic":"People & Family"},
  {"ru":"человек","en":"person","topic":"People & Family"},
  {"ru":"мужчина","en":"man","topic":"People & Family"},
  {"ru":"женщина","en":"woman","topic":"People & Family"},
  {"ru":"ребёнок","en":"child","topic":"People & Family"},
  {"ru":"родители","en":"parents","topic":"People & Family"},
  {"ru":"брат","en":"brother","topic":"People & Family"},
  {"ru":"сестра","en":"sister","topic":"People & Family"},
  {"ru":"дедушка","en":"grandfather","topic":"People & Family"},
  {"ru":"бабушка","en":"grandmother","topic":"People & Family"},
  {"ru":"время","en":"time","topic":"Time & Calendar"},
  {"ru":"сегодня","en":"today","topic":"Time & Calendar"},
  {"ru":"завтра","en":"tomorrow","topic":"Time & Calendar"},
  {"ru":"вчера","en":"yesterday","topic":"Time & Calendar"},
  {"ru":"день","en":"day","topic":"Time & Calendar"},
  {"ru":"неделя","en":"week","topic":"Time & Calendar"},
  {"ru":"месяц","en":"month","topic":"Time & Calendar"},
  {"ru":"год","en":"year","topic":"Time & Calendar"},
  {"ru":"утро","en":"morning","topic":"Time & Calendar"},
  {"ru":"день","en":"afternoon","topic":"Time & Calendar"},
  {"ru":"вечер","en":"evening","topic":"Time & Calendar"},
  {"ru":"ночь","en":"night","topic":"Time & Calendar"},
  {"ru":"всегда","en":"always","topic":"Time & Calendar"},
  {"ru":"никогда","en":"never","topic":"Time & Calendar"},
  {"ru":"сейчас","en":"now","topic":"Time & Calendar"},
  {"ru":"еда","en":"food","topic":"Food & Drink"},
  {"ru":"хлеб","en":"bread","topic":"Food & Drink"},
  {"ru":"мясо","en":"meat","topic":"Food & Drink"},
  {"ru":"рыба","en":"fish","topic":"Food & Drink"},
  {"ru":"сыр","en":"cheese","topic":"Food & Drink"},
  {"ru":"овощ","en":"vegetable","topic":"Food & Drink"},
  {"ru":"фрукт","en":"fruit","topic":"Food & Drink"},
  {"ru":"кофе","en":"coffee","topic":"Food & Drink"},
  {"ru":"чай","en":"tea","topic":"Food & Drink"},
  {"ru":"молоко","en":"milk","topic":"Food & Drink"},
  {"ru":"пиво","en":"beer","topic":"Food & Drink"},
  {"ru":"вино","en":"wine","topic":"Food & Drink"},
  {"ru":"завтрак","en":"breakfast","topic":"Food & Drink"},
  {"ru":"обед","en":"lunch","topic":"Food & Drink"},
  {"ru":"ужин","en":"dinner","topic":"Food & Drink"},
  {"ru":"дом","en":"house","topic":"House & Home"},
  {"ru":"комната","en":"room","topic":"House & Home"},
  {"ru":"дверь","en":"door","topic":"House & Home"},
  {"ru":"окно","en":"window","topic":"House & Home"},
  {"ru":"кровать","en":"bed","topic":"House & Home"},
  {"ru":"стол","en":"table","topic":"House & Home"},
  {"ru":"стул","en":"chair","topic":"House & Home"},
  {"ru":"кухня","en":"kitchen","topic":"House & Home"},
  {"ru":"ванная","en":"bathroom","topic":"House & Home"},
  {"ru":"птица","en":"bird","topic":"Nature & Animals"},
  {"ru":"дерево","en":"tree","topic":"Nature & Animals"},
  {"ru":"солнце","en":"sun","topic":"Nature & Animals"},
  {"ru":"луна","en":"moon","topic":"Nature & Animals"},
  {"ru":"цветок","en":"flower","topic":"Nature & Animals"},
  {"ru":"небо","en":"sky","topic":"Nature & Animals"},
  {"ru":"море","en":"sea","topic":"Nature & Animals"},
  {"ru":"гора","en":"mountain","topic":"Nature & Animals"},
  {"ru":"город","en":"city","topic":"City & Places"},
  {"ru":"улица","en":"street","topic":"City & Places"},
  {"ru":"школа","en":"school","topic":"City & Places"},
  {"ru":"больница","en":"hospital","topic":"City & Places"},
  {"ru":"магазин","en":"store","topic":"City & Places"},
  {"ru":"ресторан","en":"restaurant","topic":"City & Places"},
  {"ru":"вокзал","en":"station","topic":"City & Places"},
  {"ru":"парк","en":"park","topic":"City & Places"},
  {"ru":"машина","en":"car","topic":"Transportation"},
  {"ru":"автобус","en":"bus","topic":"Transportation"},
  {"ru":"поезд","en":"train","topic":"Transportation"},
  {"ru":"самолёт","en":"airplane","topic":"Transportation"},
  {"ru":"лодка","en":"boat","topic":"Transportation"},
  {"ru":"быть","en":"to be (permanent)","topic":"Action Verbs"},
  {"ru":"находиться","en":"to be (temporary)","topic":"Action Verbs"},
  {"ru":"иметь","en":"to have","topic":"Action Verbs"},
  {"ru":"делать","en":"to do / to make","topic":"Action Verbs"},
  {"ru":"идти","en":"to go","topic":"Action Verbs"},
  {"ru":"приходить","en":"to come","topic":"Action Verbs"},
  {"ru":"видеть","en":"to see","topic":"Action Verbs"},
  {"ru":"говорить","en":"to speak","topic":"Action Verbs"},
  {"ru":"есть","en":"to eat","topic":"Action Verbs"},
  {"ru":"пить","en":"to drink","topic":"Action Verbs"},
  {"ru":"спать","en":"to sleep","topic":"Action Verbs"},
  {"ru":"писать","en":"to write","topic":"Action Verbs"},
  {"ru":"читать","en":"to read","topic":"Action Verbs"},
  {"ru":"гулять","en":"to walk","topic":"Action Verbs"},
  {"ru":"бежать","en":"to run","topic":"Action Verbs"},
  {"ru":"покупать","en":"to buy","topic":"Action Verbs"},
  {"ru":"продавать","en":"to sell","topic":"Action Verbs"},
  {"ru":"понимать","en":"to understand","topic":"Action Verbs"},
  {"ru":"знать","en":"to know (a fact)","topic":"Action Verbs"},
  {"ru":"хороший","en":"good","topic":"Descriptive (Adjectives)"},
  {"ru":"плохой","en":"bad","topic":"Descriptive (Adjectives)"},
  {"ru":"большой","en":"big","topic":"Descriptive (Adjectives)"},
  {"ru":"маленький","en":"small","topic":"Descriptive (Adjectives)"},
  {"ru":"горячий","en":"hot","topic":"Descriptive (Adjectives)"},
  {"ru":"холодный","en":"cold","topic":"Descriptive (Adjectives)"},
  {"ru":"новый","en":"new","topic":"Descriptive (Adjectives)"},
  {"ru":"старый","en":"old","topic":"Descriptive (Adjectives)"},
  {"ru":"красивый","en":"beautiful","topic":"Descriptive (Adjectives)"},
  {"ru":"быстрый","en":"fast","topic":"Descriptive (Adjectives)"},
  {"ru":"медленный","en":"slow","topic":"Descriptive (Adjectives)"},
  {"ru":"счастливый","en":"happy","topic":"Descriptive (Adjectives)"},
  {"ru":"грустный","en":"sad","topic":"Descriptive (Adjectives)"},
  {"ru":"красный","en":"red","topic":"Colors & Shapes"},
  {"ru":"синий","en":"blue","topic":"Colors & Shapes"},
  {"ru":"зеленый","en":"green","topic":"Colors & Shapes"},
  {"ru":"желтый","en":"yellow","topic":"Colors & Shapes"},
  {"ru":"черный","en":"black","topic":"Colors & Shapes"},
  {"ru":"белый","en":"white","topic":"Colors & Shapes"},
  {"ru":"один","en":"one","topic":"Numbers & Math"},
  {"ru":"два","en":"two","topic":"Numbers & Math"},
  {"ru":"три","en":"three","topic":"Numbers & Math"},
  {"ru":"четыре","en":"four","topic":"Numbers & Math"},
  {"ru":"пять","en":"five","topic":"Numbers & Math"},
  {"ru":"шесть","en":"six","topic":"Numbers & Math"},
  {"ru":"семь","en":"seven","topic":"Numbers & Math"},
  {"ru":"восемь","en":"eight","topic":"Numbers & Math"},
  {"ru":"девять","en":"nine","topic":"Numbers & Math"},
  {"ru":"десять","en":"ten","topic":"Numbers & Math"},
  {"ru":"книга","en":"book","topic":"Misc & Core Vocab"},
  {"ru":"ручка","en":"pen","topic":"Misc & Core Vocab"},
  {"ru":"деньги","en":"money","topic":"Misc & Core Vocab"},
  {"ru":"любовь","en":"love","topic":"Abstract Concepts"},
  {"ru":"мир","en":"world","topic":"Abstract Concepts"},
  {"ru":"жизнь","en":"life","topic":"Abstract Concepts"}
];

export const CONJUGATIONS = [];
export const GRAMMAR_QUESTIONS = [
    {
        sentence: "Я хочу стать врачом.",
        en: "I want to become a doctor.",
        question: "Why is 'врачом' (doctor) in the Instrumental case?",
        options: [
            "It is the direct object of the sentence.",
            "After verbs of becoming and being (стать, быть), the predicate is typically in the Instrumental case.",
            "It indicates motion towards the doctor.",
            "It shows possession."
        ],
        answer: 1,
        explanation: "In Russian, nouns that follow verbs denoting a change of state, profession, or being (like стать - 'to become' or быть - 'to be' in past/future) are placed in the Instrumental case."
    },
    {
        sentence: "Завтра мы идём в кино, а потом едем в Москву.",
        en: "Tomorrow we are walking to the cinema, and then driving to Moscow.",
        question: "What is the specific difference between 'идти' (to go) and 'ехать' (to go)?",
        options: [
            "'Идти' means to go on foot, while 'ехать' means to go by a vehicle.",
            "'Идти' is for the future tense, 'ехать' is for the past.",
            "'Идти' means to go by a vehicle, 'ехать' means to go on foot.",
            "There is no difference; they are perfect synonyms."
        ],
        answer: 0,
        explanation: "Russian verbs of motion distinguish between mode of transport. 'Идти' means walking or moving under one's own power, whereas 'ехать' specifies using transport."
    },
    {
        sentence: "Он читал книгу, но не прочитал её.",
        en: "He was reading the book, but didn't finish reading it.",
        question: "What grammatical concept is demonstrated by the verbs 'читал' and 'прочитал'?",
        options: [
            "Gender agreement",
            "Case declension",
            "Verbal aspect (Imperfective vs. Perfective)",
            "Mood (Indicative vs. Subjunctive)"
        ],
        answer: 2,
        explanation: "'Читал' is imperfective (focuses on the process of reading), while 'прочитал' is perfective (focuses on the completion/result of the action)."
    },
    {
        sentence: "Я вижу красивую девушку.",
        en: "I see a beautiful girl.",
        question: "What cases are 'красивую девушку' in?",
        options: [
            "Nominative",
            "Genitive",
            "Dative",
            "Accusative"
        ],
        answer: 3,
        explanation: "They are in the Accusative case, serving as the direct object of the verb 'вижу' (to see). For feminine singular nouns ending in -а, the Accusative ending is -у."
    },
    {
        sentence: "У меня есть брат.",
        en: "I have a brother.",
        question: "Literally translated, what is the structure of this Russian sentence?",
        options: [
            "I possess a brother.",
            "To me there is a brother.",
            "By me there is a brother.",
            "My brother is here."
        ],
        answer: 2,
        explanation: "Russian lacks a direct equivalent to the verb 'to have'. Instead, it uses the preposition 'У' (by/at) + Genitive pronoun 'меня' (me) + 'есть' (is/exists) + Nominative subject 'брат' (brother)."
    }
];
export const IDIOMS = [
    {
        phrase: "Делать из мухи слона",
        literal: "To make an elephant out of a fly",
        meaning: "To make a mountain out of a molehill / to exaggerate",
        usage: "Use this when someone is overreacting to a small problem.",
        example: "Не делай из мухи слона, это всего лишь царапина!",
        category: "Frustration"
    },
    {
        phrase: "Водить за нос",
        literal: "To lead by the nose",
        meaning: "To deceive or trick someone",
        usage: "Used when someone is stringing you along with false promises.",
        example: "Он меня уже месяц водит за нос с этими деньгами.",
        category: "Social Life"
    },
    {
        phrase: "Без сучка, без задоринки",
        literal: "Without a knot, without a snag",
        meaning: "Without a hitch / perfectly smoothly",
        usage: "To describe an event or plan that goes perfectly.",
        example: "Концерт прошел без сучка, без задоринки.",
        category: "Work & Business"
    },
    {
        phrase: "Как две капли воды",
        literal: "Like two drops of water",
        meaning: "Like two peas in a pod / exactly alike",
        usage: "To describe two people or things that look identical.",
        example: "Братья похожи как две капли воды.",
        category: "People & Family"
    },
    {
        phrase: "Витать в облаках",
        literal: "To hover in the clouds",
        meaning: "To have one's head in the clouds / be daydreaming",
        usage: "To describe someone not paying attention.",
        example: "На уроке он постоянно витает в облаках.",
        category: "Personality & Mind"
    },
    {
        phrase: "Ни пуха ни пера!",
        literal: "Neither down nor feather!",
        meaning: "Break a leg! / Good luck!",
        usage: "Said to someone before an exam or big performance.",
        response: "К чёрту! (To the devil!)",
        example: "Завтра экзамен. Ни пуха ни пера!",
        category: "Opportunity"
    },
    {
        phrase: "Бить баклуши",
        literal: "To beat wooden blocks",
        meaning: "To twiddle one's thumbs / to slack off",
        usage: "To complain about someone who is lazy or avoiding work.",
        example: "Хватит бить баклуши, пора работать!",
        category: "Work & Business"
    },
    {
        phrase: "Заморить червячка",
        literal: "To starve the little worm",
        meaning: "To take the edge off one's hunger / grab a bite",
        usage: "Said when you want to eat a small snack before a main meal.",
        example: "Давай заморим червячка перед ужином.",
        category: "Food & Daily Life"
    },
    {
        phrase: "Когда рак на горе свистнет",
        literal: "When the crayfish whistles on the mountain",
        meaning: "When pigs fly / never",
        usage: "To express that something will never happen.",
        example: "Он вернет долг, только когда рак на горе свистнет.",
        category: "Social Life"
    },
    {
        phrase: "Вешать лапшу на уши",
        literal: "To hang noodles on the ears",
        meaning: "To tell tall tales / to lie or deceive",
        usage: "To accuse someone of blatantly lying to you.",
        example: "Хватит вешать мне лапшу на уши, я знаю правду!",
        category: "Communication"
    }
];
export const CONVERSATION_TOPICS = [
    "Твои увлечения и хобби (Your hobbies and interests)",
    "Любимая еда и рестораны (Favorite food and restaurants)",
    "Планы на будущее (Plans for the future)",
    "Русская литература и кино (Russian literature and cinema)",
    "Твой родной город (Your hometown)",
];
export const SENTENCE_BUILD_PROMPTS = [
    { prompt: "Describe what you did this morning.", en_hint: "Use past tense perfective or imperfective verbs depending on completion", topic: "daily routine" },
    { prompt: "Say where you live and what your city is like.", en_hint: "Use 'Я живу в...' (Prepositional case)", topic: "city" },
    { prompt: "Ask someone how much a ticket costs.", en_hint: "Use 'Сколько стоит...?'", topic: "shopping" },
    { prompt: "Explain that you like listening to Russian music.", en_hint: "Use 'Мне нравится слушать...' + Accusative", topic: "preferences" },
    { prompt: "Tell a friend you are going to the store.", en_hint: "Use 'Я иду в...' (Accusative for destination)", topic: "errands" },
];
export const VIDEOS = [];
export const CULTURE = [];

export const PROGRESSION = [
    "Basics & Greetings",
    "Food & Drink",
    "Nature & Animals",
    "Numbers & Math",
    "Time & Calendar",
    "Action Verbs",
    "Descriptive (Adjectives)",
    "People & Family",
    "House & Home",
    "City & Places",
    "Transportation",
    "Abstract Concepts",
    "Misc & Core Vocab"
];
